### ISSUE TITLE
Localisation of Open Data Certificate - additional licenses options for Italian jurisdiction

### ISSUE THREAD

**Issue by sumikasan** [theodi/shared#282]
Need to update the Italian version of the questionnaire so it includes two more open data licenses. The schema of the italian open data licences are:

1) IODL 2.0 (Italian Open Data Lincence ver 2.0)
http://www.dati.gov.it/iodl/2.0/
This is an attribution licence

2) IODL 1.0 (Italian Open Data Licence  ver 1.0)
http://www.formez.it/iodl/
This is a share alike licence with an explicit compatibility with the ODbL 1.0 and CC-BY-SA 3.0

Note:
The licence with the version 2.0 has less restrictions than the version 1.0

**Comment by Floppy** [comment]
@pkqk is this one sorted now, or are we still waiting?

**Comment by pkqk** [comment]
Questions have `Sì` and `No` as answers and the two `IODL` licences are options so I think so.
