### ISSUE TITLE
Move CSVlint file storage out of MongoDB

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#463]
CSVlint filled its database, and stopped working. I’ve added another shard, but that’s only a temporary solution, and I’m not sure of the cost impact if we leave it too long. We need to spend a little time making it more space and cost-efficient. We know what needs doing (moving storage to block store instead of MongoDB), but we need to spend the time to do it before too long.

**Comment by quadrophobiac** [comment]
will be pairing with @bcouston from Wed morning onwards on this

**Comment by bcouston** [comment]
Updated description:
CSVLint's current functionality is that it stores uploaded files.

Originally there were two possible solutions.

1. Move file storage to a better suited file store. Possibly cloud storage such as rackspace.

2. Remove persistent storage of CSV files as they are only used for a few functions that only need a file to be stored temporarily.

After discussion with @pezholio we have determined solution two is the best solution.

@Floppy also suggested moving file handling into a seperate class. For tidier code and easy to track functionality. Probably under the lib directory.

**Comment by quadrophobiac** [comment]
Potential related bug.
* run server via foreman or whatever
* upload fixtures/csvs/revalidate
* user is presented with validation screen with message "Congratulations! Your CSV is valid!" but with a 'Structural problem warning'
*If 'CR-LF' "\r\n" is selected from 'Line terminator' drop down and revalidate clicked then 1 * Structural Error is returned, however no subsequent option to revalidate is provided
* if "LF\n" is selected from 'Line terminator' drop down and Revalidate clicked 2 * 'Structural problem warnings' are returned on a refreshed validation screen
* if Line Terminator "\r\n" selected and revalidate clicked rails terminates with a Bad URI exception 
bad URI(is not URI?):

**Comment by quadrophobiac** [comment]
- [ ] Isolate existing specs and scenarios describing the behaviour which new data persistence solution must address
- [ ] Remove GridFS, substitute in tempfile or similar [BC]
- [ ] Fix the revalidation error [SF]
- [ ] Incomplete task
- [ ] Incomplete task

**Comment by bcouston** [comment]
After conversation with both Stuart and James, the decision is to keep GridFS in the application as a temporary filestore for an uploaded csv file and delete it after revalidation. This is because James stated that in production where you have more than one app server, you never know where your request will be going.

**Comment by Floppy** [comment]
PR submitted in theodi/csvlint#196

**Comment by Floppy** [comment]
Just need to work out how to run the job on a schedule.

**Comment by pezholio** [comment]
Got a PR for this here https://github.com/theodi/csvlint/pull/203
