### ISSUE TITLE
Add HTTPS to theodolite

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#481]
Does what it says on the tin.

Interactive visitors who attempt using the http version should be redirected to the https version. This applies also to deep linking (apache rewrite-style).

The APIs should not be redirected (for some reason one could want to use the http version).

**Comment by Floppy** [comment]
Probably do this with Cloudflare, otherwise:

* [ ] buy certificate
* [ ] apply to Heroku

**Comment by pikesley** [comment]
Cloudflare will work magically if we're using
* www.openaddressesuk.org
* openaddressesuk.org

If we're sticking with _alpha._ then we need to pay Cloudflare, or buy a certificate and put it on Heroku.
Opinions?

**Comment by pikesley** [comment]
I think we should buy a cert, FWIW

**Comment by Floppy** [comment]
probably best.

**Comment by Floppy** [comment]
We're not changing domain yet, so let's do that. Then it's registered to the right company etc.

**Comment by pikesley** [comment]
I have spoken to Peter about this, we will get it sorted

**Comment by pikesley** [comment]
![screenshot 2015-01-07 09 56 41](https://cloud.githubusercontent.com/assets/885973/5643725/b94c541c-9653-11e4-91d2-a37fe53afbdd.png)

**Comment by giacecco** [comment]
@pikesley don't forget to assign me the task when you hand the ball over to me, I did not realised you had gave me instructions! It's done:

```
Added ssl:endpoint to pacific-beyond-9370 ($20/mo). Next add your certificate with `heroku certs:add PEM KEY`.
```

**Comment by giacecco** [comment]
How is it going @pikesley ?

**Comment by pikesley** [comment]
This is applied and working, do we want to *force* SSL?

https://alpha.openaddressesuk.org/

**Comment by JeniT** [comment]
I don't see any harm in doing so?

**Comment by pikesley** [comment]
OK, I think this is an app thing: http://readysteadycode.com/howto-setup-ssl-with-rails-and-heroku

@pezholio how do you feel about this?

**Comment by pezholio** [comment]
I'm cool wid dat :+1:
