### ISSUE TITLE
Run trial of Turbot as ETL hosting platform

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#482]
This includes:
- [x] learning and attempting setup on our own, by Weds 7/1 
- [x] the hands-on session with Seb Bacon on Thu 8/1, 10:30 - 13:00, for anything we did not understand or is not documented
- [ ] some trial implementation, perhaps even porting the Companies House ETL to Turbot, by Mon 12/1
- [x] on Tue 13/1, with @JeniT, we decide if investing in Turbot is the wise thing to do

**Comment by pezholio** [comment]
Right, so we have successfully set Turbot up, and have run a trial of a simple bot running from end to end. I'm going to email Seb now, and see if they're OK with us forking the Turbot server and hosting it publicly, and then the next step is bending Turbot client, Turbot server and Morph to our will, but I guess this will be for the next sprint.
