### ISSUE TITLE
Design how to update 'raw' OA data model and database implementation to be fully "time aware"

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#483]

**Comment by Floppy** [comment]
Design first, then discuss implementation.

**Comment by Floppy** [comment]
Consider also how to handle negative information points, like "I know this address does *not* exist"

**Comment by pezholio** [comment]
Can anyone remind me what we mean by 'time aware'?

**Comment by giacecco** [comment]
Information coming from ETLs is associated to a period of time within which the address is known to exist. E.g. Companies House's addresses are associated to some event in the life of a company, e.g. its incorporation date or the date when the list of directors changed. We need to prepare storing this information, as it will feed into the calculation of statistical confidence.

**Comment by pezholio** [comment]
Ah, yes. I remember now. Maybe something we can discuss tomorrow when we're all in?

**Comment by giacecco** [comment]
I believe there is not much to say actually. When ETLs call the ingestion API they should simply specify a set of validity periods, e.g.

```
[ 
    { "dateStart": '"2015-01-14T00:00:00.000Z"',
      "dateEnd": '"2015-01-14T23:59:59.999Z"' },
    { "dateStart": '"2014-07-01T00:00:00.000Z"',
      "dateEnd": '"2014-07-31T23:59:59.999Z"' },
]
```

**Comment by giacecco** [comment]
Hi @floppy, how come this is got back to the backlog?

**Comment by Floppy** [comment]
Because we didn't have time for it in this sprint, and it wasn't critical for the work we did want to do. If that's changed, we can consider bringing it back in.

**Comment by Floppy** [comment]
See #572
