### ISSUE TITLE
Plan support for API versioning

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#484]
We won't have separate infrastructure for Alpha and Beta. We can afford disrupt our users when we make changes, but at the same time we can be smart about it. 

One way of achieving that is keeping older versions of our APIs available for some time after they're superseded by a more recent one.

I would like the team to evaluate the complexity of implementing this 'organically' on theodolite. If the cost is acceptable, we will then proceed to the implementation possibly within the same sprint.

**Comment by Floppy** [comment]
Recommend using content type to do this properly, not paths.

**Comment by pezholio** [comment]
I guess this is all about what we mean by API changes. The API itself is very simple at the moment, and probably not likely to change massively in the future (maybe we'll add features), but the operations we have at the moment, such as searching or viewing addresses are unlikely to change (we may add things though)

What is very likely to change though are the identifiers for addresses. Are we talking about versioning those as well?
