### ISSUE TITLE
Alpha code review

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#485]
Before actual Beta dev starts, let's survey all:
- software developed, and 
- third party services supporting operations (e.g. Heroku, AWS, Redis2Go, Papertrail...) 

deployed for Alpha to understand what we are comfortable to keep and what needs changing before moving forward.

One way to do that could be splitting the work in two parts:
- [ ] @floppy or @pezholio spend some quality time reviewing the Alpha work - potentially one reviewing the other's and *vice versa*, and make a list of weaknesses and/or potential improvements
- [ ] we decide together what is worth doing and what not, and share with the rest of the team any caveats

**Comment by pezholio** [comment]
I've had a look through the main parts of the project, and raised issues where we need to reinvestigate, or change what we currently do. These are:

## Distiller

* https://github.com/OpenAddressesUK/distiller/issues/9
* https://github.com/OpenAddressesUK/distiller/issues/8
* https://github.com/OpenAddressesUK/distiller/issues/7
* https://github.com/OpenAddressesUK/distiller/issues/6

## Ernest

* https://github.com/OpenAddressesUK/distiller/issues/20
* https://github.com/OpenAddressesUK/distiller/issues/19

@floppy - Can you have a look too, and see if there's anything I've missed?

**Comment by pezholio** [comment]
We also need to reinvestigate how we're hosting the Ernest DB. At the moment, we have it hosted in AWS, as the cloud solution we had wasn't sufficient. Do we want to keep this as is for now?

**Comment by pezholio** [comment]
Also, not sure why we have NewRelic on Ernest?

**Comment by pezholio** [comment]
We can also probably delete the ClearDB MySQL cloud subscription, as it's costing us $49.99, and we're not doing anything with it
