### ISSUE TITLE
Alpha infrastucture review

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#486]
Before actual Beta dev starts, let's survey all systems deployed for Alpha to understand what we are comfortable to keep and what needs changing before moving forward.

One way to do that could be splitting the work in two parts:
- [ ] @pikesley spends some quality time reviewing the Alpha work and makes a list of weaknesses and/or potential improvements
- [ ] we decide together what is worth doing and what not, and share with the rest of the team any caveats

**Comment by pikesley** [comment]
#Open Addresses Alpha Infrastructure

##Core components

###Ernest

* Sinatra app
* Single Heroku node
* MariaDB-as-a-Service

###Distiller

* Rake task
* Mongo-as-a-Service

###Theodolite

* Rails app
* Single(?) Heroku node
* Mongo-as-a-Service

###Hiphopapotamus

* Rake task
* Mongo-as-a-Service
* S3
* Torrents

###Indigester

* Quick-and-Dirty ETL
* Single S3 node
* Very disposable

##Also

###Turbot

Turbot comes in 3 main pieces:

####Turbot server

* Rails app
* MySQL
* Redis
* All on one 1GB Droplet

####Gitlab

* Omnibus package
* Requires a 2GB Droplet

####Morph

* Docker server
* Rails app
* Requires a 4GB Droplet
