### ISSUE TITLE
Setup analytics for OA downloadable editions

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#488]
**In time by the official Alpha launch on 14/1**, develop the Google Analytics setup to include good visibility of the number of users attempting the download of the .torrent files. 

Design the solution so that is aggregates the analytics of the same .torrent across different editions (e.g. different dates in the filename of the same version).

Find a way so that the main performance indeces (e.g. the total number of downloads) can be automatically integrated on the website, e.g. in a banner in the homepage saying "The OA datasets has been downloaded 1,453,432 times.".

~~What cost-effective options are available to monitor bittorrent traffic (see for example [here](http://www.wired.co.uk/news/archive/2012-01/27/musicmetric))?~~

@peterkwells may have specific requests around this subject.

**Comment by peterkwells** [comment]
Comments on #489

**Comment by giacecco** [comment]
About the need of updating the GA scriptlet, this is what the GA portal tells us we should use:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55858108-1', 'auto');
  ga('send', 'pageview');

</script>
```

This is what the GEM produces now:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55858108-1', {});
  ga('send', 'pageview');
</script>
```

The only difference is the ```auto``` @pezholio already knew about. Can you please confirm this does not need action, too? Thanks.

**Comment by giacecco** [comment]
For @JeniT and @peterkwells: the consolidated analytics across different editions can be read by going to https://www.google.com/analytics/web/?hl=en#report/content-pages/a55858108w89135809p96063036/ and filtering by regular expressions such as ```^/torrent\?file=\d{4}-\d{2}-\d{2}-openaddressesuk-full.json.zip.torrent$``` for the full, non-split, JSON version. I am checking with @pezholio if we can "save" these searches for re-use and across users.
