### ISSUE TITLE
Setup analytics for OA publication API

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#489]
As for https://github.com/theodi/shared/issues/488, **in time by the official Alpha launch on 14/1**, but for OA's publication APIs.

**Comment by pezholio** [comment]
[This](https://github.com/hybridgroup/gabba) might be A Thing

**Comment by peterkwells** [comment]
Some sequenced (highest priority first) thoughts. All idealised thoughts with tech/phase reality/capacity able to intervene and shift things to Beta.

1. All performance data should be open data available in both machine and human-readable formats

2. When publishing stats our users will want URI/website search/bittorrent/API usage to be correlated  *at each subset*. As a simple parallel see paper/digital application counts to Voter Registration, two channels to the same underlying service/component/data: https://www.gov.uk/performance/register-to-vote/registrations-breakdown

3. Needs to be able to evolve to support Quality Measures:

<---- extract from draft text ----->

++ Usage

People selecting address products want to know if other people are satisfied with it. A good proxy for this measure is whether the address product, or a subsection of it, that they are interested in is being used.

To meet this need address products should provide information on:

how often their bulk product has been downloaded in the last time period
how often detailed address records have been searched for in the last time period (this may be through websites or APIs)

<---- end extract from draft text ----->

There's a similar quality measure for freshness/currency which is measured by the number of  adds/changes/deletes. How detailed should a subsection (postcode/street/town/etcetera) be? That's probably a tradeoff of cost/value but as granular as we can afford.

4. Needs to be able to evolve to support *potential* chargeable models

e.g. <XXXX reads/day = free, XXXX-<XXXXX reads/day = 1 groat, >XXXXX reads/day = 0.00001 groat per read.

Therefore ability to track and analyse user/organisation accessing data via API is key and may need to be architected in early, Multi-user orgs would be useful, probably not essential but if possible then go for it.

**Comment by pezholio** [comment]
This will all be achievable (from what I understand), but my understanding is that for this task we're only going to be adding analytics to Google Analytics for the API views. Releasing the data openly and adding dashboards etc, will be a separate piece of work

**Comment by giacecco** [comment]
The natural thing is to go in order of priority. From now to the official lunch on Tues next week the most we can afford is just what is described in the original task, otherwise Peter risks not having even that. 

All other features described by Peter will compete for time and budget vs everything else during Beta, I'm meeting him tomorrow for him to give us prioritisation of the larger tech delivery picture. Moreover, many of the features are very Beta-ish, e.g. the more rigorous measurement of the dataset's quality or the support to potential business models, and I don't see a practical need for those within the next two weeks.

@peterkwells you ok with this?

**Comment by pezholio** [comment]
I've tested this on a test GA account and confirmed it to be working. @peterkwells - I think you might need to change the main domain to the alpha domain for it to work on the proper OA Analytics account.

**Comment by giacecco** [comment]
@peterkwells leave this to me

**Comment by giacecco** [comment]
@pezholio I realise now that we were talking about the *API* analytics. On Monday you seemed doubtful we could use GA for the API. Did you find a way to make that work and can you tell me more and/or show me where to see the reports?

In the meantime I've configured GA to consider all these four domains as part of the same property:
http://openaddressesuk.org
https://openaddressesuk.org
http://alpha.openaddressesuk.org
https://alpha.openaddressesuk.org
