### ISSUE TITLE
Build and deploy the "free-text addresses ETL"

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#490]
- [ ] Re-write as a re-usable software component the algorithm that is currently part of the Corporates House ETL that interprets free-text addresses. 
- [ ] Make it available internally to OA...
- [ ] ... **and** externally as an API, e.g. to be used by the upcoming [pure JavaScript ETL](https://docs.google.com/a/openaddress.es/spreadsheets/d/1grVK-aNcSQrwNjSH-eBj1sD4_6YLo8Bt7JRhZqpLm_M/edit?usp=sharing) (AKA, the "pizza delivery" scenario lightweigth client-side integration).
- [ ] Link the OA website to the new component, so that addresses being submitted interactively by users are actually processed for real rather than simply stored for later
- [ ] After [the Turbot decision is taken](https://github.com/theodi/shared/issues/482), modify the Companies House ETL to use the new component

**Comment by pezholio** [comment]
For information, here's @jenit's work that I was talking about:

https://github.com/theodi/parse-uk-addresses

We could use a combination of this and the [work we've already done in distiller](https://github.com/OpenAddressesUK/distiller/blob/master/lib/distil.rb) to create a gem, which we can then expose using a web service.

**Comment by JeniT** [comment]
Just to note that I've heard criticism of that work and it might be worth discussing with experts rather than adopting it (or not - the criticism wasn't concrete iirc).

**Comment by pezholio** [comment]
I've done a skeleton app here:

https://github.com/OpenAddressesUK/sorting_office

The hardest part of this is going to be extracting address parts from bare strings. Getting postcodes is easy (just a regex) and posttowns are pretty simple too (there are only a limited number), but localities and streets may be a little trickier. I can't see anything in the Companies House ETL that extracts address elements from bare strings, as my understanding is that the addresses are already split (albeit into Address 1, Address 2 etc), but I could be wrong (my Python knowledge is pretty patchy too)

**Comment by Floppy** [comment]
Presumably https://github.com/OpenAddressesUK/common-ETL/blob/master/address_lines.py is the relevant code in common-ETL. Looks like it's matching against the database of posttowns, OS locator, etc.

**Comment by Floppy** [comment]
Do we actually want to port this to Ruby, or shall we implement a wrapper in Python? What would porting give us, apart from being in a language we know better? If we port, then we won't be able to get updates from @MurrayData...

**Comment by pezholio** [comment]
One of the advantages would be that we can plug in the Mongoid models we have already and (assuming we're connected to the same database) return the URI of each address part too, which would be really useful. Also, it would be easier for us to maintain long term.

**Comment by Floppy** [comment]
Yeah, that's true. I wonder what @giacecco thinks.

**Comment by Floppy** [comment]
have pinged @murraydata to see if he has any test data: https://github.com/OpenAddressesUK/common-ETL/issues/10

**Comment by Floppy** [comment]
Rough translation of the relevant parts of https://github.com/OpenAddressesUK/common-ETL/blob/master/CH_Bulk_Extractor.py: https://gist.github.com/Floppy/ac87f1e53142cea445a1

**Comment by pezholio** [comment]
Now live and done at https://sorting-office.openaddressesuk.org/

**Comment by giacecco** [comment]
Sweet :-D 

@pezholio I believe we need to do two more things I did not think of specifying before, though:

a) all addresses being submitted should also be saved for our own use (@peterkwells I guess we need to state that we're doing that, in the instruction page you see when calling the sorting office without parameters?), and
b) we should return the provenance of the reference tables we use for the normalisation; by specifying some *noprov* option the user could turn that off

**Comment by pezholio** [comment]
Yeah, I think well need a new issue for this to be honest. I think 2 points should be enough.

**Comment by giacecco** [comment]
Even before the new features, I put this back in testing because it looks too easy to break, check https://github.com/OpenAddressesUK/sorting_office/issues/4 out.

**Comment by peterkwells** [comment]
If we were to automatically submit addresses to the platform because they were searched for then we'd need to present the user with the submissions guidelines as per the submit form. (If via API then we'd need that guidance to go up as part of our rules for implementing the API.)

For our own website that feels like a thing where we need to consider the UX. How to get the submission guidelines in without damaging the search flow?

Note that the search page already has a loop via the text (didn't find what you were looking for? why not submit an address)

**Comment by pezholio** [comment]
I've now fixed the breaking requests. I've moved this to done, and will now start looking at the extra features.

**Comment by giacecco** [comment]
The additional reqs are now at https://github.com/theodi/shared/issues/509 . @peterkwells has a very good point, see how I managed that in the new specs.
