### ISSUE TITLE
Write contribution guide for Open Addresses

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#491]
Writing document initially in https://docs.google.com/a/theodi.org/document/d/18KgCc34tS6I3tBJEc4WduFEU6l65u0LdBgT2PsqJybM/edit#

**Comment by Floppy** [comment]
https://github.com/tessel/contribution-guide is an interesting reference.

**Comment by Floppy** [comment]
@pikesley @pezholio can you take a quick read through the doc linked at the top here? What did I miss?

**Comment by Floppy** [comment]
@giacecco you may also want to comment on this.

**Comment by pezholio** [comment]
To be clear, is this a contribution guide for the main project, or the ELTs? This seems to lean more towards contributing to the core project, or am I wrong?

**Comment by Floppy** [comment]
For the moment, this is generic to all code. I imagine we'd add more detailed guidance for specific projects as we go on (like how to write a scraper, etc)

**Comment by Floppy** [comment]
@giacecco @peterkwells where would you like this to live? Could go on the forum wiki, the main theodolite site, or we could create a jekyll developers site.

**Comment by peterkwells** [comment]
One for @giacecco but maybe a sticky in the text on the developer's forum? https://github.com/OpenAddressesUK/forum

**Comment by pezholio** [comment]
This seems good to me :+1:
