### ISSUE TITLE
Gitlab server setup

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#499]
Or could it be done with GitHub?

For OpenAddressesUK/roadmap#56

**Comment by Floppy** [comment]
We've got turbot pushing to github successfully. Just testing the morph end.

**Comment by Floppy** [comment]
Also, morph has successfully checked out the code.

**Comment by Floppy** [comment]
This is *very* promising.

**Comment by pikesley** [comment]
I think we can close this, can't we?

**Comment by pezholio** [comment]
Yeah, totally

**Comment by Floppy** [comment]
Let me finish the code tidyup first. Tests and stuff.

**Comment by Floppy** [comment]
Upstream PR for opencorporates to review at https://git.opencorporates.com/chris/turbot_server/merge_requests/20.

**Comment by Floppy** [comment]
Our own master PR is at https://git.opencorporates.com/openpostcodes/turbot_server/merge_requests/2. We can review and merge this one.

**Comment by Floppy** [comment]
NOPE NOPE NOPE ignore me.

**Comment by Floppy** [comment]
RIGHT: this one: https://git.opencorporates.com/openpostcodes/turbot_server/merge_requests/3
