### ISSUE TITLE
Turbot server setup

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#500]
For OpenAddressesUK/roadmap#56

**Comment by Floppy** [comment]
Waiting for opencorporates to give us access to generalised code

**Comment by pezholio** [comment]
We have a running Turbot. We'll need to make some tweaks to get it working properly for us, but it's all deployed and working nicely

**Comment by pikesley** [comment]
Yes, it works, it's at turbot.openaddressesuk.org, but it's still covered in Open Corporates branding. @giacecco, we need somebody to take a look at this pls.

**Comment by giacecco** [comment]
@pikesley be more specific what do you need? Removing the OC logo and replacing it ours and some acknowledgement and thanks to OpenCorporates for maintaining the original Turbot should not be an issue. Or I'm misunderstanding you?

I can prepare the image myself if you need to.

**Comment by pezholio** [comment]
Yeah, that's the easy bit, I think we'll need to tweak some wording too, which will probably need input from @peterkwells and/or Comms. Can probably be done as part of #529
