### ISSUE TITLE
Morph server setup

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#501]
Something something tutum.co

For OpenAddressesUK/roadmap#56

**Comment by pezholio** [comment]
We now have this:

https://github.com/OpenAddressesUK/chas

To get the rest of the pieces into place we need to:

- [ ] Adapt the schemas in https://github.com/openc/turbot-client to support addresses
- [ ] Work out how to pick up the output of the scrapers and import them into Ernest. Open Corporates have Angler (code is in the Gitlab instance), but we may want something a bit more lightweight
- [ ] (Optionally) allow people to add private env variables (a la Travis) and add them to the manifest.json - something something private public keypair - This will help if we want to have the code that currently imports user-submitted addresses running in Turbot
