### ISSUE TITLE
Javascript address submission

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#505]
For OpenAddressesUK/roadmap#16 and OpenAddressesUK/roadmap#17

**Comment by Floppy** [comment]
We're going to update the website to submit via sorting office, as that now does all the required work.

**Comment by pezholio** [comment]
I think we've covered https://github.com/OpenAddressesUK/roadmap/issues/17 now. @giacecco when you talk about the PJSETL, do you want us to handle the address searching and everything, so it can be integrated into a user's website?

**Comment by Floppy** [comment]
This is done, as other search work is in another roadmap ticket (OpenAddressesUK/roadmap#35)
