### ISSUE TITLE
Single-address ETL bot (Turbot)

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#506]
For OpenAddressesUK/roadmap#52

**Comment by giacecco** [comment]
**DO NOT DEPLOY BEFORE https://github.com/theodi/shared/issues/507 **

**Comment by pezholio** [comment]
I've written a quick script that will put the addresses we've had so far in the Google Doc (which I've exported as a CSV) into the RabbitMQ queue, which this can then consume:

https://gist.github.com/pezholio/61ed2547c01daa7c0310

I've not run it yet, but will do in the morning after standup

**Comment by giacecco** [comment]
Ok I would like to understand more how "final" this is. From the sound of it, it is more of a temporary solution until we have the Turbot-based ETL.

Please also remember that no addresses submitted by the public should be published (API or Bittorrent) before we're also [ready to take them down](https://github.com/theodi/shared/issues/507). Are you working on the live data or some sandbox?

**Comment by Floppy** [comment]
No, the idea here is that sorting office now queues addresses for processing by the single-address ETL. What @pezholio has written is a script that will go through the googledoc and send them to sorting office. It's just a one-time thing. We can explain in standup.

**Comment by pezholio** [comment]
I've been thinking about this and I'm wondering - do we want this to be a bot in Turbot? The main issue is because the single addresses are published to IronMQ now, we have to have the access token and project ID in the code. If we pushed it to Turbot, we'd have to have the token published in GitHub, which obviously is a bad idea.

**Comment by pezholio** [comment]
Or do we want to somehow allow people to add environment variables to turbot through the command line, or encrypted via the manifest.json (in a similar way to how Travis handle environment variables)

**Comment by giacecco** [comment]
The design principle is that we do not want to maintain two different ingestion workflows, including all the side features of that such as take down etc.

**Comment by pezholio** [comment]
Oh yeah, totally. Having this in Turbot *feels* much nicer. I guess I'm trying to work out how best to organise it.

**Comment by giacecco** [comment]
I would love to have more time to help you on that :-(((

**Comment by giacecco** [comment]
See https://github.com/theodi/shared/issues/512 . This is suspended until the next sprint.

**Comment by giacecco** [comment]
Postponed to *after* #41

**Comment by Floppy** [comment]
Waiting until we can deploy chas update, once the CH ETL has finished.

**Comment by Floppy** [comment]
Happening in http://github.com/OpenAddressesUK/sorting_machine

**Comment by giacecco** [comment]
You mean "sorting_office" ;-)

**Comment by Floppy** [comment]
Nope, I just got the wrong link: https://github.com/oa-bots/sorting_machine :)
