### ISSUE TITLE
Definition of manual takedown process and terms

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#507]
I see from https://github.com/OpenAddressesUK/roadmap/issues/25#issuecomment-70505121 that it was agreed that manual takedown of bad data will suffice for the time being. I'm happy with that.

I believe though that we need:

a) instructions that are sufficiently clear for anyone in the Tech Team - including the dummies like myself - to run the process safely and without assistance, including taking down and recovering from takedown, if it was a "false alarm"
b) some degree of testing, possibly as part of the testing of https://github.com/theodi/shared/issues/506 when the feature starts being needed, and
c) a *gentlemen's agreement* on the service level we commit to internally (takedown only, recovery is best effort). E.g. the data must be taken down and a new edition of the dataset issued within *X* hours from request in GitHub (e.g. three calendar days, to manage incidents that take place over the weekend)
d) to prepare the template for the page publishing the list of the deprecated downloadable editions, with accompanying text stating that they contain data which has since been placed in quarantine and should not be used

@JeniT and @PeterKWells may have a better idea of how quick that *X* at point (c) above should be.

Please remember takedown should be implemented as a *logical deletion*. Later assessments could suggest data can be re-integrated in the dataset.

**Comment by giacecco** [comment]
Blocked awaiting @giacecco and @peterkwells to decide if even this is overkill.

**Comment by giacecco** [comment]
@peterkwells and I talked about it, he will think to what are the minimum acceptable terms of takedown and we'll determine what their implications on tech ops and features are. @JeniT likely to be involved.

**Comment by giacecco** [comment]
Internal version being reviewed at https://docs.google.com/a/openaddress.es/document/d/1ulzMDenyL3HoMvFS2F52luHMheVHG5tjRQr7MQpUw6E/edit# . Not ready for publishing beyond OA.

**Comment by pezholio** [comment]
Seems entirely sensible to me :+1:

**Comment by giacecco** [comment]
Two documents describe what we plan to do now:
- this is the [description for the public](https://docs.google.com/a/openaddress.es/document/d/1ulzMDenyL3HoMvFS2F52luHMheVHG5tjRQr7MQpUw6E/edit?usp=sharing) that has become https://alpha.openaddressesuk.org/about/reportaninfringement on the public website.
- this is the [internal process](https://drive.google.com/open?id=1u8eGjwJr7NKqkFp6xHtx0pvpE3HbztybpoqrV3iLSxU&authuser=0)

When we know from @peterkwells that the latter is final, I would like the team to make a quick final check to assess technical feasibility of everything that's described in it and then we can close this.

**Comment by peterkwells** [comment]
The internal process is ready for review by tech team. It is an MVPolicy, we will iterate as we learn through doing.
