### ISSUE TITLE
Enhancements to the search API (part 1/2)

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#508]
This is support to case (a) described at https://github.com/OpenAddressesUK/roadmap/issues/28 . I've talked to @peterkwells and we believe it is worth doing the sooner the better. 

Moreover, as user-submitted addresses start being processed, it would be disappointing if they could not come back and find them just because of this feature missing

**Comment by pezholio** [comment]
This may be a bit trickier than my first solution of just doing a regex, as this returns too many results initially. May need to use Elasticsearch, or maybe we can add indexes that make this faster

**Comment by giacecco** [comment]
I am sure we discussed search performance before perhaps with @floppy, too. 

I seem to remember we decided then that - if any of the following made search more performing or useful - it was acceptable:
- not to implement advanced search tools / methods like elasticsearch as long as the searching activity did not kill the rest of website,
- to constraint search to a minimum set of input argument, e.g. searching just by street name or just by town name, and
- to shorten the number of results, e.g. I believe that now we return an arbitrary number of results; searching for "george street" returns 41 pages of 25 addresses each across all the UK

I would like you to find a compromise between tackling the *business* requirement for this sprint while moving towards the solution we will likely implement in the upcoming ones, so that no work is wasted.

Does all of this give you sufficient direction to make a choice?

**Comment by pezholio** [comment]
The issue here is that my initial solution was using a regex for searching (so searching for "high", would result in a search for `/^high/i`), which works perfectly well in development, but less well in production when pitted against the full dataset. I've started looking at fulltext indexing now, which may be a happy medium between regex and full on Elasticsearch.

**Comment by pezholio** [comment]
I think we're going to have a job with this too, as fulltext searching (or even full-on Elasticsearch) is going to cause problems with false positives. 

Thinking around this problem, I don't think we really need to do partial matching. People aren't necessarily going to search for street names without suffixes for example. However, we might consider when people may use short form suffixes (such as 'st' for 'street' etc), and this is something we'll need too for the single addresses ETL too.

**Comment by JeniT** [comment]
@pezholio Won't ElasticSearch return a match measure for each match it finds? Can't we order by that? Can't we filter out those with a low match (experimenting a bit to determine what 'low' means)?

**Comment by giacecco** [comment]
@pezholio's idea is not bad either, though, if we could demonstrate it is more performing or cost effective; each search could be made into the union of a series of searches: the original string's + the original string concat'ed the most common 'accessory words' (how are they called?): street, st, square, sq...

Consider though that, unless we change our mind about the scenarios described at https://github.com/OpenAddressesUK/roadmap/issues/28#issuecomment-70400723 , it is not useful to implement a temporary solution that is not consistent with the endgame.

Getting ElasticSearch to rate the results vs something sensible such as the Levenshtein distance from the original search string must be feasible.

**Comment by pezholio** [comment]
I've done a bit more digging and found that you can have 'starts-with' functionality in Elasticsearch (rather than keyword matching, which is the default behaviour). This may work well for our purposes, though in order to index all the streets, we'll need to bump up our Elasticsearch index.

I'm going to have a play locally first before we commit.

**Comment by pezholio** [comment]
Blocked by not really knowing what I'm doing with ElasticSearch

**Comment by pezholio** [comment]
This was the thing I was trying http://www.elasticsearch.org/blog/starts-with-phrase-matching/

**Comment by Floppy** [comment]
Fresh pair of eyes, attempting to unblock and move this on.

**Comment by Floppy** [comment]
OK, so the sample code in that phrase matching blost definitely works locally, so now to try with some towns.

**Comment by Floppy** [comment]
OK, there are two bits to this. First, use a match_phrase_prefix search:
```
curl -X GET http://127.0.0.1:9200/towns/town/_search?pretty=true -d '{ "query" : {"match_phrase_prefix" : {"name": "FOR"}}}'
```
However, by default, this includes BLANDFORD FORUM which is shouldn't. Second step is to use the keyword tokenizer as suggested by the doc linked above.

Both those need inserting into the code separately. Now working on how to do each one.

**Comment by Floppy** [comment]
Ruby for search

```
Town.es.search(index: 'towns', body: {query: {match_phrase_prefix: {name: "FORU"}}}).first
```

Currently gives "BLANDFORD FORUM", which is wrong. Now to sort the index analyser.

**Comment by Floppy** [comment]
ruby index code:
```
  elasticsearch!({
    index_options: {
      settings:{
        index:{
          analysis:{
            analyzer:{
              analyzer_startswith:{
                tokenizer:"keyword",
                filter:"lowercase"
              }
            }
          }
        }
      },
      mappings:{
        town:{
          properties:{
            name:{
              search_analyzer:"analyzer_startswith",
              index_analyzer:"analyzer_startswith",
              type:"string"
            }
          }
        }
      }
    }
  })
```

**Comment by pezholio** [comment]
And does that work? Looks pretty much like what I had I think

**Comment by pezholio** [comment]
However, when I was querying, I was doing `Street.es.search("Thing")`. Maybe that's where I went wrong

**Comment by Floppy** [comment]
PR now open on https://github.com/OpenAddressesUK/mongoid_address_models/pull/7

**Comment by Floppy** [comment]
Once that one's in, we can update the Gemfile.lock and merge https://github.com/OpenAddressesUK/sorting_office/pull/11

**Comment by Floppy** [comment]
And then we can use it in theodolite as well.

**Comment by pezholio** [comment]
Cool, nice work! we'll probably need to up our Bonsai ElasticSearch account before this makes it into production. The streets index is over 1GB on my machine.

**Comment by Floppy** [comment]
Right, sorting office is using this successfully now.

**Comment by giacecco** [comment]
Hi All, what's the situation with this? I see that 'starts-with-phrase' still does not work with the live search. Thanks.

**Comment by Floppy** [comment]
This is now working as well as we can get it. You may get 0 results if you don't provide enough information (search for all streets starting with a single letter, for instance), but we've pushed elasticsearch as far as we know how at the moment, and that's a pretty strange use case. We'll see if anyone reports it as an error. However, this certainly now supports typing in the first part of a road name (bluebell, for instance) and getting the results back. Also, partial towns are supported. See https://alpha.openaddressesuk.org/addresses?street=Nuthurst&town=Hors for an example of partial search on both fields.

**Comment by giacecco** [comment]
Hurray!
