### ISSUE TITLE
sorting_office enhancements

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#509]
Follow-up to https://github.com/theodi/shared/issues/490 . Resources freed thanks to the 2 points saved by postponing https://github.com/theodi/shared/issues/503 to later sprints.

Please add the following two features to *sorting_office*:

a) add an argument representing if the user of the API accepts OA's submission guidelines or not; if she does, all addresses being submitted for normalisation should also be processed for our own use through #506 (when it's ready). See also @peterkwells at https://github.com/theodi/shared/issues/490#issuecomment-70815698 .

b) the results should include the provenance of the reference tables we use for the normalisation; by specifying some *noprov* argument the user could turn that off

Note that, because *sorting_office* is supposed to be used internally to OA, too, the provenance information we return is not just a formality but is fed to all other OA software components that use sorting_office for their own work, e.g. the updated Companies House ETL.

**Comment by pezholio** [comment]
With regard to a) - my understanding was that this was to be used as a tool for ETLs to parse address strings too - this means that when an ETL gets run, we'll get two addresses, one from sorting-office and one from the ETL itself. Is that OK? Also this means we won't be tracking the provenance of addresses added via an ETL

**Comment by giacecco** [comment]
I believe you mean b), not a).

It don't think it is like you describe. Most ETLs will do this:

1) read their own data (e.g. Companies House's downloaded zip files)
2) for each address, if needed, call *sorting_office* to replace the original with the normalised one
3) submit the normalised address to the Ingester

This means that the ETL provenance **will** include a reference to the fact that it used sorting-office to parse the address.

This means that, perhaps, the original address is written somewhere in the provenance, but ETLs will give the Ingester just the parsed address, exactly as they do now, not two addresses.

What do you reckon? Call me if not clear, I'll be available until 2 UK time.

**Comment by pezholio** [comment]
Oh no, I get that, but if we're saving addresses submitted via sorting_office, and ETLs use sorting_office too, we'll get this pattern:

1) ETLs read an address line
2) The address line is passed to sorting_office
3) sorting_office parses the address AND saves the address to be processed by #506 
4) The parsed address is returned
5) The ETL submits the parse result

The result of which will be that we have two addresses saved in ernest, one which has the provenance of being a user-submitted address and another which has the correct provenance of coming from a given dataset.

We could get round this by making sure any wrapper library passes a flag to say that the address shouldn't be saved, or allow users to POST a provenance record (but this would still mean we would have two addresses saved - one potentially with slightly different provenance)

Does that make sense?

**Comment by giacecco** [comment]
You are right, this is very interesting.

The point is that we are allowing anyone to use *sorting_office*, not necessarily just ETLs, and this means that the "second address" may never come.

At the same time, it is useful to avoid duplicates, as they would artificially inflate the confidence in those addresses being normalised by ETLs using *sorting_office* vs the ETLs that don't need *sorting_office* (e.g. Land Registry's Price Paid, if we could use it).

The solutions you offer are good but there may be another one that also addresses original point (a). Rather than a ```--nosave``` flag, we may implement a ```--contribute``` one, that simultaneously acts as a statement that the user of the API accepts OA's submission guidelines and there won't be a duplicate submission later.

What do you think?

**Comment by pezholio** [comment]
OK, good shout. I like this :+1:

**Comment by pezholio** [comment]
b) has now been implemented :dancers:
