### ISSUE TITLE
Investigate failed individual member capsule store

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#510]
Kat signed up, but her details are sitting in the services queue and haven't been added to capsule. Need to work out why.

**Comment by pezholio** [comment]
Oh, wait. Look at the code:

https://github.com/theodi/open-orgn-services/blob/master/lib/capsulecrm/save_membership_details_to_capsule.rb

It runs `find_organisation` (https://github.com/theodi/open-orgn-services/blob/047dff4454f20105341187577665b64565473d33/lib/capsulecrm/capsule_helper.rb), which will always return nil. We need to change this to look for an organisation first, and, if it's nil, try and find a person

**Comment by Floppy** [comment]
Oh, whoops. It never calls #find_person at all?

**Comment by pezholio** [comment]
Nah man

**Comment by Floppy** [comment]
That wasn't the root cause, though we have fixed it.

@georgiap @greenreveller the problem with individual members not appearing in CapsuleCRM is down to the Xero sync system creating new members in Capsule as organisations, not people, so our searches fail. We've got in touch with CapsuleCRM to see how to resolve this, but for now, we might need to convert people from orgs to people (which is easy) when they appear. Obviously that's only a very temporary solution.

**Comment by greenreveller** [comment]
Great - for the time being you can pull up a list of individual supporters here: https://theodi.capsulecrm.com/parties/list/106274

James, I can't see how to convert orgs to people in Capsule (only the other way around - can you show me how when you're in? thanks).

**Comment by Floppy** [comment]
Confirmed all the data has now gone in, so this was definitely the problem.

The convert option is in the dropdown next to their picture.

![screen shot 2015-01-28 at 11 52 18](https://cloud.githubusercontent.com/assets/3565/5937158/2a8acaa0-a6e4-11e4-9103-c6d01f7ba596.png)

Discussion with Capsule is progressing. It looks like this will be a bit of a pain, but there are some things we can do...

**Comment by Floppy** [comment]
Closing this for now as we know the problem, and we'll open a new issue for the proposed solution when we have one.

**Comment by greenreveller** [comment]
Thanks @Floppy but I can't see the 'convert to person' option (only convert to org)?

**Comment by Floppy** [comment]
Oh, yes, they are already people, we've done them. You'll see "convert to person" on organisations. If that makes sense.

**Comment by greenreveller** [comment]
ah ok, so i'll keep doing that up until the problem is fixued


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @UKODImembers
<https://twitter.com/UKODImembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002
