### ISSUE TITLE
OA Website: blog and news sections improvements

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#514]
@peterkwells please specify here your requirements for:

- [ ] sorting of [news items](https://openaddressesuk.org/about/news)
- [ ] sorting of [blog items](https://openaddressesuk.org/about/blog)
- [ ] display of author name associated to the above

Other?

**Comment by peterkwells** [comment]
As per feedback from users

1) sort all lists (news/blog) with newest date at the top
2) Display the author name which is in the markdown

We could go further (name tags/search functions etc.) but they don't seem needed yet. Let's keep iterating and learning....

Either Emma or Peter can do simple validation with the dev.
