### ISSUE TITLE
Rationalise Linodes

### ISSUE THREAD

**Issue by pikesley** [theodi/shared#520]
We still have 3 running, probably need only one

**Comment by JeniT** [comment]
Find out what's running on which Linodes & see if we can switch some off.

**Comment by pikesley** [comment]
Unless I've missed something, there are only 2 running now. One of them is the Chef server and needs to remain.

**Comment by pikesley** [comment]
On the other one, it's running MySQL but I'm pretty certain it's not in use:

    mysql> show databases;
    +-----------------------------+
    | Database                    |
    +-----------------------------+
    | information_schema          |
    | member_directory_production |
    | mysql                       |
    | odi_drupal                  |
    | performance_schema          |
    | test                        |
    +-----------------------------+
    mysql> use member_directory_production;
    Database changed
    mysql> select id, created_at from members;
    +----+---------------------+
    | id | created_at          |
    +----+---------------------+
    |  8 | 2013-03-04 09:29:27 |
    |  9 | 2013-03-07 14:04:19 |
    | 10 | 2013-03-07 14:48:46 |
    | 11 | 2013-03-09 11:29:51 |
    | 12 | 2013-03-09 11:33:26 |
    | 13 | 2013-03-11 11:13:04 |
    | 14 | 2013-03-13 10:05:16 |
    | 15 | 2013-03-20 21:22:32 |
    | 16 | 2013-03-21 11:49:51 |
    +----+---------------------+  
    9 rows in set (0.00 sec)

**Comment by pikesley** [comment]
Redis is also here. It's running the services-manager queue. The machines that are connecting to it are:

    backend-quirkafleeg-01
    backend-quirkafleeg-02
    backend-quirkafleeg-03
    directory-01
    directory-02
    services-manager-01

So for now, this is Critical Infrastructure. These could be migrated to somewhere else, though.

**Comment by pikesley** [comment]
Further investigation suggests that the only thing we care about on here is Redis. Once we've moved that elsewhere, we can shut this box off.
