### ISSUE TITLE
Validation APIs

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#523]
Create APIs that allow users to confirm or negate the existence of an address or any part of it. Optionally, the claim includes:
- timestamp the claim refers to (defaults to the API call timestamp)
- free-text reason for the claim
- free-text attribution statement

Indicative examples below:

```
curl --data "exists=true&attrib=@giacecco was here&timestamp=2015-01-21T16:18:32+00:00" https://openaddressesuk.org/validation/addresses/V16up8
```

confirms the existence of our London address;

```
curl --data "exists=false&reason=I went there and there was nothing" https://alpha.openaddressesuk.org/validation/addresses/V16up8
```

negates it;

```
curl --data "exists=false" https://openaddressesuk.org/validation/streets/4T3OPv
```

negates the existence of Clifton Street (this will be useful when we start accepting addresses that are not in the reference tables).

The domain will be prefixed by _alpha._ as long as we do the same for the other APIs.

Data from the single claim submissions will be stored in our "raw database" individually, rather than consolidated. As for "bad addresses" we need to be able in the future to take down validation claims, too.

**Comment by Floppy** [comment]
I'm thinking we add a validation model to the ernest data model. A validation can derive from an address. We can then follow the provenance chain for an address to build another address with a confidence measure based on the validations.

**Comment by Floppy** [comment]
Ideally this data would flow directly into the ernest API, as it's part of the full data model. Interesting that we need to match to IDs from theodolite though.

**Comment by Floppy** [comment]
I'd suggest the URL structure of the form {address_url}/validations though, and a POST to create a new one.

**Comment by Floppy** [comment]
Should every validation produce a new derived address automatically, or should that be a post-processing step, I wonder?

**Comment by Floppy** [comment]
Stepping back from the validation products - this ticket is just about storing those validations. Also, any object in the ernest DB can have a validation on it.

**Comment by Floppy** [comment]
Completed and working. API interface can be seen in https://github.com/OpenAddressesUK/ernest/blob/master/spec/api/validation_spec.rb and will be included in the documentation we write for ernest/turbot under a separate ticket.

**Comment by Floppy** [comment]
Verified working with live system - a POST to the right address places a validation record into the database. What we do with it, well that's the next stage.

**Comment by giacecco** [comment]
@floppy about [your comment](https://github.com/theodi/shared/issues/523#issuecomment-74686809) about the documentation, I believe we need it to be very independent from Turbot's. It is not difficult to imagine many applications using the search and validation APIs independently of anything else. 

I suggest that the best way of doing this is to offer an interactive / instruction landing page on the style of what @pezholio's done for Sorting Office at https://sorting-office.openaddressesuk.org/ . What do you reckon?

**Comment by giacecco** [comment]
@Floppy I've tried the JSFiddle example with my home address https://alpha.openaddressesuk.org/addresses/UAdD1o.json but I'm not getting the "OK" back, can you please check it's working?

In general, what's the easiest way for me to check the contents of ernest, e.g. for debugging what just went wrong? Just want to look into it, not fiddle with anything. I never had the time to try, and it may be useful for the OD Camp. Ta.

**Comment by Floppy** [comment]
validations aren't exposed in ernest at the moment, which is slightly annoying. Maybe I'll make a resource to show them. Currently the only way is with the console, which @pezholio has just checked and verified it's all working. There is a PR about to merge to get this on the website.

Agreed on documentation, I didn't mean to imply that it would be part of the turbot docs, but part of the ernest API docs, which don't really exist yet and need writing. We could add that as a simple page on ernest.openaddresses.org if you want, as sorting office does, yes.

**Comment by Floppy** [comment]
I was having a conversation with Peter about API docs; let's talk about that at standup.
