### ISSUE TITLE
Integrate validation APIs in the search pages

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#524]
Following https://github.com/theodi/shared/issues/523 , add to the search results:

- at the top of each page: a discrete "Do you want to validate this results?" question
- if the user says yes to the above, two buttons appear  on the side of each address being displayed:  indicative labels "This address exists" and  "This address does not exist" 

clicking on the buttons calls the respective validation API in the background. The "attrib" field is populated with something like "Validation through the Open Addresses UK website.".

This feature should be suitable to be used as OA's official example of how to use the validation APIs. Keep this in consideration when writing. E.g. full client-side implementation is preferable.

**Comment by Floppy** [comment]
Unfortunately an ernest API key is required, so we will have to have some of it server side.

**Comment by giacecco** [comment]
Well it's the validation APIs "server" that need the ernest API key, not the client to the validation APIs, correct?

**Comment by Floppy** [comment]
The validation API is only in ernest (currently). Wherever it was though, we'd want some sort of API key for the validation API, wouldn't we, but you don't really want those things leaking client side.

**Comment by giacecco** [comment]
I agree, but at the same time we have already decided to cater also for low quality, anonymous contributors. In the same way we get addresses from anyone on the website and Sorting Office, we should be able to do the same for validation what do you reckon? Can you Hangout at around 2?

**Comment by Floppy** [comment]
OK, I can easily make validation not require the API key; that's easy enough to do.

**Comment by Floppy** [comment]
No need for hangout unless you've got anything else you want to cover.

**Comment by giacecco** [comment]
I've spoken to @peterkwells, too, about this. For the time being we need to be a little looser and allow anonymous validation information submission, too. 

Note, this is not _in alternative_ to what you've done already, but in addition.

It is good that validation through the website's search result pages is recognised as such thanks to the API key reference. But we also need an anonymous API to do the same that we can ask people to temporarily reference from their own apps without the overhead of registration.

**Comment by Floppy** [comment]
UI question - do we want this on the search page, or on the individual address page? That's a lot of buttons to add to a search result page, it might be better on the single-address page (as an example, at least).

**Comment by peterkwells** [comment]
Recommend starting with individual address page, similarly we currently only allow individual address submission. Just as we will use a UX bod to gradually allow multiple address entry we can gradually allow multiple address validation. The platform can support it, the UX is all about how we expose it.

re: anonymous or not to be anonymous. There's a whole governance piece around the APIs that needs exploring before the end of this phase: issuing keys, recovering keys, deliberately abusive usage, etcetera.

**Comment by giacecco** [comment]
+1 for the individual address page.

**Comment by Floppy** [comment]
great. I'm working on this in pure javascript, so we can have something people can just drop in easily.

**Comment by Floppy** [comment]
Took a while to get the CORS stuff sorted, but this jsfiddle does it: http://jsfiddle.net/udc7w1np/. Will add the UI first thing, shouldn't take long.

**Comment by Floppy** [comment]
OK, this is all done now. There is a single javascript file at https://alpha.openaddressesuk.org/assets/validate_address.js which has a function which wraps the validation API.
