### ISSUE TITLE
Port the Companies House ETL to Turbot

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#527]
... unless this was done already to test Turbot thus far.

Evaluate also options for the automation of the ETL execution. Companies House issues new data at the beginning of each month.

**Comment by pezholio** [comment]
Pushed to https://github.com/oa-bots/companies_house - Gonna wait for it to run and see if we get anything sensible out of it. @floppy, could you clone and run locally and see if anything blows up?

**Comment by pezholio** [comment]
So, this crapped out on two runs in Chas (basically on the sorting office run), so I've added some code that retries requests to Sorting Office (I am kicking the you know what out of it) and am running it again.

**Comment by Floppy** [comment]
This processed 1.5million addresses before crapping out on a bad CSV (file 4, if I remember correctly). The resulting output was 1.7GB, which will make IronMQ absolutely shit itself, so we need to cut up the output or process it as it goes along. We considered adding each output line to the queue separately. I suspect this will want to be a job for next sprint. The ETL bot Stuart has written is working as intended though, there are just some other issues around it.

**Comment by giacecco** [comment]
Thanks @floppy. So, for clarity, we still cannot offer a downloadable version of the data more recent than 10 December, correct? 

We're also not been running the serialisation for a long time, are we sure that - when we'll be ready again - it will run nicely? FYI @pezholio.

**Comment by giacecco** [comment]
Re-opened, as in the end we weren't successful.

**Comment by giacecco** [comment]
Hi @pezholio, by closing this do you mean that we've also completed successfully an ingestion of the latest CH data?

**Comment by pezholio** [comment]
No, that job's in https://github.com/theodi/shared/issues/569

**Comment by giacecco** [comment]
Sorry
