### ISSUE TITLE
"Camera ready" setup of all components to be offered at the Open Data Camp

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#529]
See https://github.com/OpenAddressesUK/roadmap/issues/74 . Is it useful to allocate points for this, to be sure we have resources in the days before the event?

The activity includes:
- [ ] run the ingestion of Companies House's latest data, using the new Turbot-based ETL or the old one, whichever is available
- [x] James' doc
- [ ] others?
- [x] Branding of http://turbot.openaddressesuk.org/ (Paint it orange, add our badge, remove their words, thank them? - see #534)

**Comment by JeniT** [comment]
- [ ] contribution guidance

**Comment by giacecco** [comment]
@pezholio @floppy @pikesley also note that @peterkwells has started preparing [here](https://docs.google.com/a/openaddress.es/document/d/17L8g3v3n_Dk4CqK6WYShm_Ze1p_AaBoCnK53DFYG5Ro/edit?usp=sharing) a todo list with a wider scope than tech we should check the sprint work we are doing against. Ask if anything is not clear.

**Comment by pezholio** [comment]
This is The Big List of Things We Need To Do To Get Turbot Running

- [ ] Add a schema for addresses to our fork
- [ ] Pull the new schema into turbot-client and turbot-runner
- [ ] Get a new fork of turbot-runner into Github (need to speak to Seb about this)
- [ ] Fork the [Morph Docker Image](https://github.com/openc/morph-docker-ruby) and reference our version of turbot-runner (and optionally the gems we want to allow)
- [ ] Work out if there's an easy way to monitor bot's HTTP requests while they're running in our Docker instance to build provenance
- [ ] Add OA branding to turbot-client

Anything I've missed?

**Comment by Floppy** [comment]
Right, all the documentation is complete, and linked from the tech docs in the appropriate places. I'm concerned that that document is far too long and we could do with a simple quickstart, but I'll ask @peterkwells about that once we get to ODCamp.

**Comment by Floppy** [comment]
Actually the turbot docs need deploying - @pikesley will do that once we land at ODCamp as well.
