### ISSUE TITLE
Consider node website questions

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#541]
Some time required to consider the following from @langphil:

We are looking at potentially employing Wordpress multi-site to centralise and manage the Node websites that are upcoming. I wanted to run this solution past you to consider the following aspects;

* What amount of time / tech team resources would you envisage (if any) this setup would take?
* We need to consider the management of URL's across the node website. Any thoughts?
* Considering Google Analytics. Would this sort of setup play towards an automated approach? Google Analytics and Google Spreadsheets integration.
* The building of node Dashboards. Just placing it on your agenda as Gavin will likely want this at some stage as it is a good way of the nodes to see how others are doing
* Any other considerations you can think of.

**Comment by sumikasan** [comment]
Also see:
https://github.com/theodi/shared/issues/518
