### ISSUE TITLE
Support recording a confidence measure within Open Addresses

### ISSUE THREAD

**Issue by JeniT** [theodi/shared#545]
So the data schema includes a confidence score.

**Comment by giacecco** [comment]
@pezholio @floppy learn about confidence by following these simple four steps:
a) read the blog post at https://alpha.openaddressesuk.org/blog/2015/02/20/confidence
b) read the specifications of the scoring system at https://docs.google.com/a/openaddress.es/document/d/1955JNRhDGMckIRObgS-9cEduY5p6cX6fKMjY-peSE8Q/edit 
c) ask @giacecco about what you did not get, and
d) ask @murraydata to to see how the algorithms and the calculations look like

**Comment by pezholio** [comment]
I've added basic score calculation to the address as can be seen in https://github.com/OpenAddressesUK/ernest/blob/confidence/lib/models/address.rb#L17

This gets the statistical confidence for the towns and streets, calculates the total confidence, applies the heuristic adjustment (using the `created_at` date for now), and then applies the Companies House weighting (hard coded for now).

Bear in mind that this is slow as hell at the moment, so there's still some optimisation work to be done.

**Comment by Floppy** [comment]
:+1: I can take a look at speeding it all up with indexes etc next week. Sweeet.

**Comment by pezholio** [comment]
Oh, and the build is broken at the moment, because there's some massively weird shit going on - *maybe* to do with Database Cleaner. The tests work fine in isolation, but all together the scores change ¯\_(ツ)_/¯
