### ISSUE TITLE
Add submission guidelines / acceptance to Turbot

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#548]
@peterkwells requires this as an urgent change, feel free to drop lower priorities OA features from the sprint if necessary.

We should:

- Reference the guidelines in Turbot's *homepage, use Sorting Office as a model, and

**AND**

- ... as part of the ETL registration process, users must be shown the submission guidelines and state to have read and accept them for the process to proceed. It is part of the ETL registration process as each ETL can have different sources etc.

We will leave for later other features such as:

- Re-confirm the acceptance for each ETL if we change the guidelines.

**Comment by peterkwells** [comment]
I have _not_ urgently requested the AND clause (to make this part of the registration process). That is tracked in roadmap feature #79.

My request was simply to change the static text. I'd do it myself it I knew where it was .....

**Comment by giacecco** [comment]
Ok fall back to the first part only. The "... as part of the ETL registration process, (...)" goes into the wishlist for later stages.

@pikesley, James suggested you can do that, so that we leave him and Stu to work with John on inference implementation.

**Comment by pikesley** [comment]
Not sure I understand the intent here, do we want the text from [here](https://github.com/OpenAddressesUK/roadmap/issues/79#issue-57287306) on the Turbot front page?

**Comment by giacecco** [comment]
Practically yes but for the stuff that does not apply. I suggest you continue the paragraph starting with "Welcome to Turbot! This is where..." with this text:

```
Welcome to Turbot! This is where Open Addresses hosts its own and our contributors' ETLs and inference engines. 

Before you start contributing, please review the guidelines below.

We do not want to receive any names in the submission, other than any company name that may form part of the address. The Open Addresses data that we publish will be about locations, not about people.

Please be sure not to violate others' intellectual property or privacy rights with your submission. If you think your Intellectual Property rights are being infringed then please [report the infringement](https://openaddressesuk.org/about/reportaninfringement).

When you register your ETL we will ask you to provide additional information about your ETL, its objectives, its source data etc. This information is used to track submissions and as part of our processes to track provenance and to remove any data that is unlawful. Find out more about our [privacy policy](https://openaddressesuk.org/about/data/privacy).

By submitting an address you are saying that Open Addresses Limited can re-use the address and publish it under an open data licence. You are saying that the publication of the address by Open Addresses Limited or third parties does not and will not infringe any of your legal rights or those of any third party.
```

The "start contributing" button could also be renamed into "I accept the submission guidelines and want to start contributing". Not snappy, but says it all.

**Comment by pikesley** [comment]
Pushing to Tutum right now.

**Comment by pikesley** [comment]
Done: http://turbot.openaddressesuk.org/

**Comment by giacecco** [comment]
Re-opened to check that @peterkwells is happy.
