### ISSUE TITLE
Add age of individual address to Ernest data model 

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#551]
From https://github.com/OpenAddressesUK/roadmap/issues/4 . 

One component of confidence scoring is a 'decay' associated to the age of the source information. 

Data sources such as Companies House's have events associated to the individual records, typically the dates when an event in the life of the company took place, e.g. constitution or the change of a director. That is the most relevant date that should be propagated to Turbot to represent that address' age.

When no such date can be specified, the moment of submission to Turbot should be used.

Blocked by #572.

**Comment by pezholio** [comment]
This work is detailed in https://github.com/OpenAddressesUK/ernest/pull/32. Probably not *quite* ready to merge, but the work is done
