### ISSUE TITLE
Fix broken lat/lon support

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#552]
This is the final fix to the issue and what @floppy refers to at https://github.com/OpenAddressesUK/theodolite/pull/117#issuecomment-76176234 .

**Comment by pezholio** [comment]
I'm taking a snapshot of the DB and trying a fix locally. If it works, then I'll run it on the live DB. This is going to have to be done very carefully though

**Comment by pezholio** [comment]
Changing the order is proving to take quite a long time. I think the best plan is to let it run locally, and then restore to production from a dump of the postcodes collection.

**Comment by pezholio** [comment]
I've updated the order locally overnight and have a dump of the postcodes collection, ready to restore. We'll then need to undo my quick fix commit here in Theodolite https://github.com/OpenAddressesUK/theodolite/commit/11d9bbcbbf1dedec6a12009ab6b9d89657e2afb6, as well as flipping the order of lat and lngsin Sorting Office.

I've also just noticed that streets are also affected, so we'll have to sort those too

**Comment by pezholio** [comment]
Ah, also localities have the same problem. This, however, means that code changes will be minimal. All we need to do is flip the latlngs and undo the temporary fix and things should carry on working fine

**Comment by giacecco** [comment]
Waiting to hear back to @peterkwells in case he was demoing the services.

**Comment by giacecco** [comment]
@pezholio Peter is fine, you can proceed.

**Comment by pezholio** [comment]
So, this is blocked due to https://github.com/mongoid/mongoid/issues/3998. I'm sure this is a bug, but I could be doing something wrong.

**Comment by pezholio** [comment]
Running this against the live DB now. Works fine in dev :+1:

**Comment by Floppy** [comment]
:shipit:

**Comment by Floppy** [comment]
Address.first and Address.lat now have correct lat/longs in postcodes, so i'm calling this done.
