### ISSUE TITLE
Data as Culture related items

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#555]
From Joe:

 the data as culture page needs a little work. The related items are not being generated in Panopticon...
they seem to be coming from elsewhere
we hoping to also get the styling cleared and the panopticon related items functionality turned on for that page. Phil said it would be a quick job but let me know if foresee any problems.

**Comment by Floppy** [comment]
I'm not exactly sure which page this is referring to. @langphil can you add any more precise detail?

**Comment by langphil** [comment]
Hi @Floppy 
The page in question is [this one](theodi.org/culture).
From what I can remember, the aside boxes were added *manually* before  we had related items functionality in the Panopticon side of publishing. What is specified in Panopticon as being a related item for this page seems to have to bearing upon what is being generated. So it is coming from elsewhere. I wanted to see if yourself or @pezholio could remember what was done. 

Thanks,

**Comment by Floppy** [comment]
Ah, I see. What needs adding? I'll add it quickly manually, or fix the underlying requirement if there is time.

**Comment by Floppy** [comment]
Yep, here they are: https://github.com/theodi/frontend-www/blob/master/app/views/content/culture_page.html.erb

**Comment by langphil** [comment]
@floppy If I replace the aside stuff with the following, will that fix it?

</div>
<% if @publication.related_links.count > 0 %>
<aside class="article-sidebar listing">
<% @publication.related_links.each do |link| %>
<div class="module module-light module-colour-<%= rand(1..12).to_i %>">
<a href="<%= link[:url] %>">
<h1 class="module-heading"><%= link[:title] %></h1>
</a>
</div>
<% end %>
</aside>
<% end %>

**Comment by langphil** [comment]
Great, if I take an aside from another page that is generating related
items correctly and replace what is here, will that fix it?

—
*Phil Lang - Digital Production Editor*
@ODIHQ <https://twitter.com/ODIHQ> | thodi.org
@langphil <https://twitter.com/langphil> | *0741 44 63047*

**Comment by Floppy** [comment]
yes, just done it - there is some shared code that we use that's now in there.

**Comment by langphil** [comment]
Thank you!!

—
*Phil Lang - Digital Production Editor*
@ODIHQ <https://twitter.com/ODIHQ> | thodi.org
@langphil <https://twitter.com/langphil> | *0741 44 63047*

**Comment by Floppy** [comment]
It's working now. Not quite as pretty, but yes, working.

**Comment by langphil** [comment]
Hi, 
I'm still seeing issues here. It now seems that the related items are being directed towards the news/blog, even though they are generic pages. 

**Links should be going to**

http://theodi.org/data-as-culture-2014

**But end up going to**

http://theodi.org/news/data-as-culture-2014

[http://theodi.org/culture](Culture page)

**Comment by Floppy** [comment]
Oh, bugger it, so they are. Hmm.

**Comment by langphil** [comment]
Hi @Floppy 

Just checking if this got resolved?

Thanks

**Comment by pezholio** [comment]
I think this is fixed? Unless I'm missing something?

**Comment by Floppy** [comment]
Yeah, this looks right to me now. How odd.

**Comment by langphil** [comment]
Yes, you are correct. Seems to have updated overnight.
