### ISSUE TITLE
Handle enormous output files from bots

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#556]
Very large output files from bots will make things explode. Add output lines individually to queue, or make turbot handle output line-by-line as bots run.

Also need to handle long-running bots without timeouts.

**Comment by Floppy** [comment]
See #527 for history

**Comment by pezholio** [comment]
I know what we need to do with this now:

* First, add the iron_mq gem to https://github.com/OpenAddressesUK/morph-docker-ruby and upload the new image to Docker
* Update the Docker images on the live Chas instance
* Then, we can update https://github.com/OpenAddressesUK/chas/blob/master/utils/wrapper.rb to send each line to IronMQ, this is what runs in the Docker image (we can also limit draft runs to 1000 records here too, which should speed things up)

**Comment by pezholio** [comment]
We can also clean loads of stuff up in https://github.com/OpenAddressesUK/chas/blob/master/lib/turbot_docker_runner.rb, and we don't need the https://github.com/OpenAddressesUK/chas/blob/master/lib/handler.rb anymore either.

**Comment by Floppy** [comment]
So the idea is we pass the IronMQ details into the docker runner, and it queues things directly, rather than all the external file-piping gubbins? How does that handle validation etc, and does it take us too far away from the OpenCorporates mainline?

**Comment by pezholio** [comment]
https://github.com/OpenAddressesUK/chas/blob/master/utils/wrapper.rb still uses TurbotDockerRunner, it just the handler that's different, and this could potentially be configurable too.

**Comment by Floppy** [comment]
We've dived into this and agree you look correct - there's more validation down there than we expected. Going to give it a go.

**Comment by pezholio** [comment]
Schaweeeet! :+1:

**Comment by Floppy** [comment]
OK, this is working in chas: https://github.com/OpenAddressesUK/chas/pull/5

**Comment by Floppy** [comment]
We're putting that onto live, testing, and then we can clear up a lot of the higher-level turbot runner / handler stuff separately.

**Comment by pezholio** [comment]
Boom, nice :+1:

**Comment by Floppy** [comment]
And sorting machine is now re-enabled and running things in through it correctly.

**Comment by Floppy** [comment]
This is all good. Well worked out, @pezholio :)
