### ISSUE TITLE
"Confidence scoring as a service"

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#560]
AKA Jess for confidence scoring. This API scores any address given as an input, including addresses that are not in the OA database, e.g. specified as free text. Includes a ```contribute``` parameters identical to Sorting Office.

**Comment by pezholio** [comment]
Thinking about this, in the spirit of 'many parts, loosely joined', we should only accept addresses in the format similar to the format we accept in Jess, i.e.

```JSON
{
  "saon": null,
  "paon": 1,
  "street": "High Street",
  "locality": null,
  "town": "Testtown",
  "postcode": "SW1A 1AA"
}
```

That way, people can use sorting-office to split addresses, and then 'pipe' the resulting data to this service to get the confidence.

**Comment by pezholio** [comment]
Also, are we doing the heuristic adjustment here too?

**Comment by giacecco** [comment]
The heuristic adjustment is an integral part of the confidence scoring, it is not an option.

If we wanted to be pedantic we may publish both the total score and its components (pre- and post-adjustment), but for the time being I would say that is overkill.

**Comment by pezholio** [comment]
OK, so if a user doesn't provide a date, do we assume today's date?

**Comment by giacecco** [comment]
I would say we use the moment of ingestion, it's all we got.

**Comment by pezholio** [comment]
This is working, but mega slow at the mo. I'm working on ways of speeding this up, inamongst other things

**Comment by pezholio** [comment]
So, I'm adding a new column called `partial_label`, and adding the postcode sectors to that. This is proving to be MASSIVELY slow though, although the pain of creation may give big benefits. We shall see...

**Comment by pezholio** [comment]
It's there, but it's slow. Going to close this for now
