### ISSUE TITLE
Add confidence to all APIs that return addresses

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#561]
Include confidence scoring to all addresses returned by any API (search, but also Sorting Office) if a ```confidence=true``` parameter or equivalent is specified.  Blocked by #560.

**Comment by Floppy** [comment]
@peterkwells can you update this to reflect what we actually want now?

**Comment by peterkwells** [comment]
We need to have a route to determine confidence via each means of service (API, bulk, URI)

API - A confidence-as-a-microservice API that can be called standalone or, say, be chained together  subsequent to a Sorting Office call that creates a structured address out of free-format, etcetera.
Downloads - already in https://github.com/theodi/shared/issues/562
URIs - confidence available via JSON

Does that make sense/seem reasonable?

**Comment by pezholio** [comment]
I'm happy about point 1) and point 3), but having the confidence in downloads worries me a bit. It's already quite a drain on performance at the mo, and even if we improve it considerably, creating confidence for every single address is going to take quite some time.

**Comment by peterkwells** [comment]
Gotcha. What I'm concerned about is creating a difference between the data that bulk download users can get, as compared to data that API users can get.

It doesn't all need doing at the same time so I'm happy to split "confidence in downloads" into a separate roadmap issue for prioritisation at another time.

Shall I do that?
