### ISSUE TITLE
Inference "run" on all past addresses

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#565]
Blocked by #504 and #569 (so that we have a fatter Companies House before we infer).

**Comment by pezholio** [comment]
Waiting for the current distil to finish, then we should be able to get a nice clear run at this

**Comment by pezholio** [comment]
Kicked this off now. It's running as we speak

**Comment by Floppy** [comment]
Is this still running?

**Comment by pezholio** [comment]
Yeah. Had to kick it off again as it crapped out though :/

**Comment by Floppy** [comment]
booo

**Comment by pezholio** [comment]
Hello Kitty has been running for three days now without a crap out. Got about 800,000 addresses going through distiller at the mo, and about 2 million in the queue ready to be processed by Ernest. I think we can call this a win

**Comment by pezholio** [comment]
This is still running, and probably will for a while, so closing
