### ISSUE TITLE
Schedule nightly runs of Hippodamus

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#566]
Blocked by #567 .

**Comment by pezholio** [comment]
OK, so I've run this again overnight and it seemed to work. I forgot to add "split" and "single" to the files though, so have set another run for tonight.

**Comment by pezholio** [comment]
Sigh. Some worked. Others didn't. No idea why.

**Comment by pezholio** [comment]
Hm. Looking in more detail, it seems that some of the processes are running out of memory. Really need to figure out a more performant way of doing exports. Mongodump would be ideal, but I think the transformations we want to do are a bit more complex than mongodump allows.

**Comment by Floppy** [comment]
Are they ways we can do this in more of a stream style, so we don't load so much in at once.

**Comment by Floppy** [comment]
We updated this to stream-style on Thursday, so we should be OK now. Just checking the outputs to make sure it worked.

**Comment by Floppy** [comment]
Actually, it's not merged yet and is in https://github.com/OpenAddressesUK/hippodamus/pull/13

**Comment by Floppy** [comment]
Merged and testing with a full run.

**Comment by Floppy** [comment]
This worked.

**Comment by Floppy** [comment]
The scheduler is updated, so this should happen on a weekly basis now automagically. Yay!
