### ISSUE TITLE
Make OA platform stats available to a "dashboard" on website

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#571]
Investigate and implement options to extract data from Google Analytics and feed it to some dashboard on the website, as part of the website revamp work. @patricejb / @peterkwells will give more detail of what exactly we need.

**Comment by patricejb** [comment]
Quite new to this, is this where you raise tickets/ queries? I'll speak with David about what data we can pull this avro.

**Comment by patricejb** [comment]
To summarise our discussion earlier the dashboard features for the home page are:
- Total number of addresses
- % Regional breakdown of addresses  - i.e. 15% of OA's addresses are addresses in the Midlands 
- Average address score percentage and daily comparative stat 
- Total number of ETLs
- Total number of addresses served through search
- Total number of addresses updated (collaborative maintenance)

Other metrics TBC for developers only.

**Comment by peterkwells** [comment]
To help design discussions here's a *draft* of the speadsheet wot I scribbled in my notebook. Feel free to comment/edit/change. I guarantee mistakes!

Note the different services, they can be 'added together' for an overview for certain types of user.

Note the desire to have our internal svce mgmt using the same stats as external detailed users, i.e. users who are interested in more than the front-page dashboard.

https://docs.google.com/a/openaddress.es/spreadsheets/d/1n72XC125FB51oXyvrowaY6pmUJJdT1dokQ1dRWmJ9GU/edit#gid=0

**Comment by Floppy** [comment]
Pull data out of metrics API (#598) and display somewhere useful.

**Comment by pezholio** [comment]
PR is here, ready for merge when you're ready @peterkwells https://github.com/OpenAddressesUK/theodolite/pull/196

**Comment by peterkwells** [comment]
Those numbers don't seem to make sense. We had c. 1m addresses and were due to infer 2-4m or so. Talk through in standup in the morning?

**Comment by pezholio** [comment]
We haven't inferred against the full dataset yet. That's happening as we speak :)

**Comment by peterkwells** [comment]
Ah, that's the whirring noise I can hear from the clouds overhead....

But the 1.9m?

**Comment by pezholio** [comment]
We picked up an extra 100,000 or so from the second Companies House ingest
