### ISSUE TITLE
UKAN dynamic badge generator

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#574]
A day's work, requested by @statshero, to do a sort of shields.io for UKAN training badge generation. Could potentially be pushed into the start of innovation week if someone fancied doing it there instead.

See https://docs.google.com/a/theodi.org/document/d/1c3ZboFFIaz7R38i6Ed3NuRvGgQXMf6Qf0haGW4qbtFk/edit for the details.

**Comment by Floppy** [comment]
I've just realised, reminded by Simon, that http://openbadges.org/ exists. We should use this.

**Comment by statshero** [comment]
Sounds good to me.

**Comment by Floppy** [comment]
@pezholio @pikesley we need to work out whether we could do an openbadges integration in the day's work that Ulrich has available for this. I hope it's easy, but I've never looked at it. If you get a spare minute between things, and fancy taking a look at how it works, feel free.

**Comment by pezholio** [comment]
Looking at http://achievery.com/ - have emailed @statshero with the details, then we can look at some deeper integration later

**Comment by Floppy** [comment]
Achievery has shut down, we can probably find an alternative.

**Comment by Floppy** [comment]
This is sitting with @statshero to decide what we want to do. Might be worth @pezholio having a chat with him to discuss some of the other options he came across?

**Comment by pezholio** [comment]
:+1:

**Comment by Floppy** [comment]
@statshero what's the state of this? I assume the deadline has whoosed by and we don't need to do it any more?

**Comment by statshero** [comment]
not for UKAN except if you have something shiny you can create in half a day.

**Comment by statshero** [comment]
Simon may still care though.

**Comment by Floppy** [comment]
Yeah, we'll park it for now though. UKAN thing done. Or not done. Over, anyway. Thanks.
