### ISSUE TITLE
configure new domain name for odmat

### ISSUE THREAD

**Issue by ldodds** [theodi/shared#586]
Can we please configure `pathway.theodi.org` to CNAME `odmat.herokuapp.com`.

Aiming to launch the alpha on Weds. If you let me know when its done, then I can sort out the Heroku bit.

**Comment by pikesley** [comment]
Done (subject to propagation time)

**Comment by pikesley** [comment]
It has propagated, you can add the virtualhost at the Heroku end

**Comment by ldodds** [comment]
done, thanks.
