### ISSUE TITLE
Node types in Publisher

### ISSUE THREAD

**Issue by langphil** [theodi/shared#587]
Hi @Floppy @pezholio @sumikasan 

This request is from the services team and is part of the Node relaunch:
At the moment Nodes can be created as one of the three in Publisher;

* City
* Country
* Comms

I am looking to make additions to these as follows;

* Learning 
* Network
* Network & Learning

**Comment by Floppy** [comment]
Will involve new tags, new options in the dropdown, and updated rendering code.

**Comment by gilesdring** [comment]
Have added in new [publisher code](https://github.com/theodi/publisher/tree/fix/shared-587) which renders as follows:

![image](https://cloud.githubusercontent.com/assets/1731108/8083983/2f2d514a-0f80-11e5-82e7-49f7cec2f4b6.png)

Underlying values are `network`, `learning`, `network_learning`, which are used as class names when rendering views. Other values remain the same.

**Comment by gilesdring** [comment]
Need to validate that the class is being added correctly: may need some guidance on setting up a test user on my local machine who can publish events, so they appear in the listing.

**Comment by Floppy** [comment]
@langphil can you assess whether this is working as expected?

**Comment by langphil** [comment]
Assessing now. 

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 16 June 2015 at 16:20:59, James Smith (notifications@github.com) wrote:

@langphil can you assess whether this is working as expected?

**Comment by langphil** [comment]
This all looks correct to me.
