### ISSUE TITLE
Review website tagging work

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#589]
Review @simonv3's work in various PRs:

* [x] https://github.com/theodi/frontend-www/pull/368
* [x] https://github.com/theodi/content_api/pull/122
* [x] https://github.com/theodi/static/pull/105
* [x] https://github.com/theodi/signonotron2/pull/38
* [x] https://github.com/theodi/publisher/pull/132

@simonv3's comments:

> I've gotten the tags working on the website (PRs #368, #122, and #105), though I'm having some issues with the tests (that I'm not sure can be traced solely to my additions). The website also has support for .json and .atom feeds for tags. URL format is /tags/<tag_name>/, and can have multiple tags /tags/<tag_name>/<tag_name>/
> I've pushed tentative updates to Publisher (PR #131) but I haven't properly handled tests on that that branch yet. Though the tests that are dying are errors more than failures, so I'm not sure they're my fault.
> Would love to hear your feedback, code-wise, PR-wise, etc.

**Comment by simonv3** [comment]
Hey @Floppy let me know if I can help somehow.

**Comment by Floppy** [comment]
@simonv3 @langphil: This is all working great: http://theodi.org/blog/data-revolution-addis-ababa-high-level-conference and http://theodi.org/tags/addis-ababa
