### ISSUE TITLE
Modules on certain pages are broken

### ISSUE THREAD

**Issue by langphil** [theodi/shared#590]
Related items on certain pages are not generating correctly. They are attempting to generate as news modules and are throwing in /news into the URL that is meant to be accessed.

For instance

* Assign theodi.org/jobs as a related item for a page
* Module generates on the page in the aside.
* When clicked the URL theodi.og/news/jobs is accessed

I'd view this as a high priority issue as we now cannot link pages together with relevant content.

**Comment by langphil** [comment]
Here is an example of an artefact that is currently in the publishing phase. 

http://theodi.org/guides/prioritise-open-data-to-drive-global-development?utf8=%E2%9C%93&cache=1427892410&edition=1&commit=Preview

NB. This may go live at some point today. If this is the case I'll exchange the related items for external related items, which are working fine.

**Comment by Floppy** [comment]
@langphil I have a theory - does this seem to happen for related items that are just plain pages, not a type like guide, or news, or event? I note on the example above, the things that are guides or news are right, it's just the generic pages that are wrong. The jobs example would be the same. Thoughts?

**Comment by langphil** [comment]
@Floppy Yes, this rings true from what I've been experiencing. 

Single page artefacts do seem to be the items that are being affected.

**Comment by Floppy** [comment]
@langphil I've found the problem and fixed it I think. Should be going live in a few minutes.

**Comment by langphil** [comment]
Thank you @floppy. This is great!

**Comment by Floppy** [comment]
@langphil that preview link above now looks right. If you're still seeing the broken version, change the cache number in the URL to bust the cached copy in your browser.
