### ISSUE TITLE
Check inference output

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#594]
Follow up results of #565 and make sure inferred addresses are appearing in the published data

**Comment by pezholio** [comment]
We got one clean run of Hello Kitty, and the addresses are waiting in the queue to be processed. May take some time though, but should be good

**Comment by pezholio** [comment]
Waiting for the current distil to finish, then we should be able to close this

**Comment by pezholio** [comment]
Whoop! We have distilled datas! Example here:

https://alpha.openaddressesuk.org/addresses/aDEWQ6
