### ISSUE TITLE
Investigate API management services

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#595]

**Comment by peterkwells** [comment]
Some prior thinking on *theoretical* analytics here. Food for thought, not requirements: https://docs.google.com/a/openaddress.es/spreadsheets/d/1n72XC125FB51oXyvrowaY6pmUJJdT1dokQ1dRWmJ9GU/edit#gid=0

**Comment by Floppy** [comment]
https://apigee.com ?

**Comment by pezholio** [comment]
This looks like the one. I've set up a proxy for sorting office at http://openaddresses-test.apigee.net/sorting-office/ and sent a couple of requests to it. It might take up to an hour for stats to start appearing, so will check back in a bit
