### ISSUE TITLE
API monitoring

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#596]
Might be easier if we can use a separate service under #595

**Comment by Floppy** [comment]
Moving this to done as apigee will do it for us.

**Comment by pezholio** [comment]
We're not using Apigee for this now for lots and lots of reasons. Mainly because the API is shonky

**Comment by pezholio** [comment]
Now using Google Analytics via https://github.com/OpenAddressesUK/angerfist, but now we need to actually get the stats out, which may be tricky, because Google APIs

**Comment by pezholio** [comment]
We're now tracking Theodolite and Sorting Office. And adding more monitoring is pretty trivial now
