### ISSUE TITLE
Website fixes post tagging work

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#599]
* [x] https://github.com/theodi/panopticon/issues/113
* [x] https://github.com/theodi/publisher/issues/133
* [x] https://github.com/theodi/panopticon/issues/114
* [x] https://github.com/theodi/publisher/issues/134
* [x] https://github.com/theodi/panopticon/issues/115
* [x] https://github.com/theodi/publisher/issues/135
* [ ] https://github.com/theodi/panopticon/issues/116

**Comment by langphil** [comment]
@floppy raising the completion of this for internal sprint
