### ISSUE TITLE
Team page (theodi.org)

### ISSUE THREAD

**Issue by langphil** [theodi/shared#601]
**Issue:** 
The [theodi.org/team](theodi.org/team) has become out of date with the developing structure of the organisation.

We currently only have a limited types of teams available that are not reflective of the current structure, with no easy way for us as users to create or assign new team types.

**Existing team types**
![screen shot 2015-04-28 at 14 26 20](https://cloud.githubusercontent.com/assets/5029907/7370538/add0a212-edb2-11e4-814d-84de2d512e44.png)

**Needs**
As users we need the ability to create and attribute team type to individuals, within the publishing process.

**Comment by langphil** [comment]
@floppy raising this for internal sprint

**Comment by Floppy** [comment]
As these are implemented using tags, we could change this to a more interactive tagging method rather than the tickboxes.

**Comment by langphil** [comment]
@gilesdring When you get to this, it'd be good to know if there is scope for a publisher to generate and remove teams on the fly via the panopticon process. If not, I will supply the names of teams that we need added / removed.

**Comment by gilesdring** [comment]
Have reused interactive keyword tagging approach to this, which means that arbitrary teams can be added.

![image](https://cloud.githubusercontent.com/assets/1731108/8161071/36b39ccc-136c-11e5-9888-c0beb1170e7f.png)

This doesn't quite get to the heart of the issue, as these are not backed with 'formal' tag types, and there is no easy way for these to be created without coding (I don't think...).

Discussing some options around this with @Floppy.

**Comment by langphil** [comment]
Thanks for the update, let me know how discussions go.

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 15 June 2015 at 14:39:06, Giles Dring (notifications@github.com) wrote:

Have reused interactive keyword tagging approach to this, which means that arbitrary teams can be added.



This doesn't quite get to the heart of the issue, as these are not backed with 'formal' tag types, and there is no easy way for these to be created without coding (I don't think...).

Discussing some options around this with @Floppy.

**Comment by Floppy** [comment]
I think it will be best to create a manual interface for managing those tags somewhere. Keyword tags are created on demand when added in the editor, but in this case I think it will be better to be a little more controlled about it.

**Comment by Floppy** [comment]
We could 'manually' create them in a database migration for now. That at least makes them fairly easy to maintain, and adding more wouldn't be too hard. I don't expect it to change that often.

**Comment by Floppy** [comment]
I'm not sure if adding them to https://github.com/theodi/panopticon/blob/master/db/seeds/tags.rb would *just work* or not. That would be good enough, probably, if it did.

**Comment by gilesdring** [comment]
Was just looking at that.

@langphil, could you provide a list of the valid teams for me to add into the migration tasks. We'll come back to you with the potentially more strategic direction. Concern is that it's a reasonably major reengineering, and could delay current implementation.

@floppy: I'm looking at the jQuery options for tagsManager. There's a validator callback, and an option to limit choices to items in the typeahead. Will let you know which looks best option.

**Comment by langphil** [comment]
Hi, 

I’ll get a list across to you this afternoon.


-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 15 June 2015 at 15:16:38, Giles Dring (notifications@github.com) wrote:

Was just looking at that.

@langphil, could you provide a list of the valid teams for me to add into the migration tasks. We'll come back to you with the potentially more strategic direction. Concern is that it's a reasonably major reengineering, and could delay current implementation.

@floppy: I'm looking at the jQuery options for tagsManager. There's a validator callback, and an option to limit choices to items in the typeahead. Will let you know which looks best option.

**Comment by Floppy** [comment]
Nice one. If it does look like if things in tags.rb are added automatically, that's the sort of thing that @langphil could do without too much trouble when he needed to, so I suspect that would be OK for now.

**Comment by gilesdring** [comment]
The tags.rb file is processed when a `rake db:seed` task is run.

**Comment by Floppy** [comment]
Ah, OK, that seems sensible. It's non-destructive though, is that right, so we can re-run whenever?

**Comment by gilesdring** [comment]
I think so. Will check. I think it attempts to delete some older stuff, which I presume was a previous dead end.

**Comment by Floppy** [comment]
@langphil this is basically done, but we need to define the new teams. The current method would be to add them in the code just like this: https://github.com/theodi/panopticon/blob/master/db/seeds/tags.rb#L79.

As it's not going to happen often, we think this is probably sufficient (for now at least). Do you want to submit a PR to that file with the new team tags you'd like to have, or would you rather provide a list here for us to create for you?

**Comment by gilesdring** [comment]
Yes. Changes are pending in the https://github.com/theodi/panopticon/tree/fix/shared-601 branch. Will create a PR for this, if required and separate the team creation into a separate PR

**Comment by langphil** [comment]
Where are we with this?

**Comment by langphil** [comment]
Just checking in, in advance for tomorrow. Would like to get this tied off.

**Comment by gilesdring** [comment]
Ok. Just waiting for names of teams to add.

**Comment by langphil** [comment]
OK,

Could we add the following, to cover all bases. 

Culture
Environment
Strategy
Franchise
Learning
Membership
Training
Evidence
Research
Services
R&D
Production
People Dev
Finance
Business Support
Technical
Intern
Board

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 7 July 2015 at 08:34:30, Giles Dring (notifications@github.com) wrote:

Ok. Just waiting for names of teams to add.

**Comment by gilesdring** [comment]
Pull Request has been created with the updated seeds file -> https://github.com/theodi/panopticon/pull/126

**Comment by Floppy** [comment]
Tweaks to that list in https://github.com/theodi/panopticon/pull/128

**Comment by gilesdring** [comment]
Ta! Hope you agree the function wrapper aids readability!

**Comment by Floppy** [comment]
definitely :)
