### ISSUE TITLE
Add ways for users to add / suggest UPRNs to existing addresses

### ISSUE THREAD

**Issue by pezholio** [theodi/shared#603]
Probably via Turbot

**Comment by pezholio** [comment]
We have this in a PR now (https://github.com/OpenAddressesUK/distiller/pull/14) - we assume that UPRNs will be added in the usual way via Turbot. When added via Distiller, if an address already exists, we load that existing address, add the UPRN and update the provenance appropriately.

**Comment by pezholio** [comment]
Thinking about this, I think we also need to cater for the circumstances when the rights for the UPRN are clear, but the address data itself may be fuzzy. Could we ask ETL writers to use the Open Addresses API to search for an address and, if we already have the address, submit the URI for the address, together with a URPN like so:

```JSON
{
  "uri": "https://alpha.openaddressesuk.org/addresses/rYwoGk",
  "uprn": "200001345656"
}
```

@jenit, @peterkwells - What do you think?

**Comment by JeniT** [comment]
I think it's useful to be able to submit a known URL for an address to add information to it, but I don't think this is necessary functionality. So low priority if there are other things to get complete.

**Comment by pezholio** [comment]
Ah, OK. I'll consider this done and add a low priority story. This was nowhere near 5 points, so we've got a bit of wriggle room.

**Comment by pezholio** [comment]
I'll wait for the current distil to finish and get feedback from @peterkwells before merging the PR and closing
