### ISSUE TITLE
Startups: updates

### ISSUE THREAD

**Issue by langphil** [theodi/shared#611]
Internal sprint request for the startup pages. This is a high priority request. The official startup programme launch is Tuesday 18/5.

We currently have a single startups page -  http://theodi.org/start-ups

I'd like to achieve the following.
1) Remove the listing of startups in the already existing page. (/startups)
2) Create a new page that o
nly lists the existing startups. (start-ups/current)
3) Create a new page that only lists graduated startups. (start-ups/graduated)

@Floppy 
@statshero @kcorrick 

**UPDATE**

Please could we also have the aside, with related internal / external items switched on for part 1 of this request (/startups).

Thanks,

**Comment by Floppy** [comment]
More outsourcing

**Comment by Floppy** [comment]
Related items addition is done.

**Comment by gilesdring** [comment]
OK - this causes a potential issue in the url mapping.

At the moment `/start-ups/current` would pull up the startup called _current_. Similarly for `/start-ups/graduated`.

Options:

1. load the routes first, so Current and Graduated become special - issue if anyone ever creates a startup called current or graduated!
2. use an extra dashed url `/start-ups-current` and `/start-ups-graduated`, which looks a bit ugly.

Thoughts...

**Comment by langphil** [comment]
If we were to go for the first option, how would startups who have graduated or are current have their URL’s generated?

Would it be;

theodi.org/startups/current/startups-name
theodi.org/startups/graduated/startups-name

cc @statshero

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 9 June 2015 at 16:06:49, Giles Dring (notifications@github.com) wrote:

OK - this causes a potential issue in the url mapping.

At the moment /start-ups/current would pull up the startup called current. Similarly for /start-ups/graduated.

Options:

load the routes first, so Current and Graduated become special - issue if anyone ever creates a startup called current or graduated!
use an extra dashed url /start-ups-current and /start-ups-graduated, which looks a bit ugly.
Thoughts...

**Comment by JeniT** [comment]
Once a startup has a page, we don't want to change their URL: you shouldn't have URLs for individual startups that have a changeable status component within them. I'd suggest:

/startups/startups-name - consistent URL for the startup
/graduated-startups - list of graduated startups
/startups - list of current startups

**Comment by gilesdring** [comment]
The `/start-ups` page has been simplified to remove the current lists. How about:

`/start-ups` - general information
`/start-ups/name` - consistent URL for the startup
`/current-start-ups` - list of current startups
`/graduated-start-ups` - list of graduated startups

Need also to define navigation between the various pages. Will discuss with Phil tomorrow.

**Comment by Floppy** [comment]
Looks to me like http://theodi.org/current-start-ups and http://theodi.org/graduated-start-ups are working. Hurrah! Also http://theodi.org/start-ups is now not showing the list, as expected. Presumably we just need @langphil to define the navigation to the list pages now?

**Comment by langphil** [comment]
I’ve added the related links in on /start-ups. 

These have been added as external related items.

**Question**

In panopticon, for related artefact (not external related items), will these two new pages appear in the dropdown of pages for association. 

I’d prefer to have them as related artefacts, over external related items. 

Thanks

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 10 June 2015 at 17:30:08, James Smith (notifications@github.com) wrote:

Looks to me like http://theodi.org/current-start-ups and http://theodi.org/graduated-start-ups are working. Hurrah! Also http://theodi.org/start-ups is now not showing the list, as expected. Presumably we just need @langphil to define the navigation to the list pages now?

**Comment by Floppy** [comment]
As those pages aren't artefacts in the CMS as such, they wouldn't appear in that list. We could *make* artefacts for them, like we have for /start-ups. That would mean you could also edit intro text if you wanted any.

**Comment by langphil** [comment]
That would be very useful. 

How difficult is this process. It’d be good to know how this is achieved. 

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 11 June 2015 at 09:05:19, James Smith (notifications@github.com) wrote:

As those pages aren't artefacts in the CMS as such, they wouldn't appear in that list. We could make artefacts for them, like we have for /start-ups. That would mean you could also edit intro text if you wanted any.

**Comment by Floppy** [comment]
I think if you create the pages with the right stubs in publisher, then we can easily copy the code from the old page to pull in the new content. Let us know when they're there; shouldn't take a minute.

**Comment by langphil** [comment]
They’ve been added in publisher, with the relevant stubs.

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 11 June 2015 at 09:30:48, James Smith (notifications@github.com) wrote:

I think if you create the pages with the right stubs in publisher, then we can easily copy the code from the old page to pull in the new content. Let us know when they're there; shouldn't take a minute.

**Comment by Floppy** [comment]
@gilesdring reckon you can copy the artefact code from the startups action to the new ones to display these in the new pages?

**Comment by gilesdring** [comment]
Should be able to do this. Will put it on list for next week, unless I get the events stuff done rapidly.

**Comment by langphil** [comment]
Hi, 

Just to update. 

I've added a few new startups into the system this morning. 

They've been marked as current startups.

They have so far failed to generate on the website here - [http://theodi.org/current-start-ups](http://theodi.org/current-start-ups)

Just flagging it. I"ll keep an eye on it.

Any thoughts?

**Comment by Floppy** [comment]
@langphil can you assess whether this is working as expected, for the basic lists as originally specified?

**Comment by langphil** [comment]
Assessing now.


-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 16 June 2015 at 16:21:30, James Smith (notifications@github.com) wrote:

@langphil can you assess whether this is working as expected, for the basic lists as originally specified?

**Comment by langphil** [comment]
The only change to this that I would make is in relation to the related items. 

Adding external links in Panopticon as external related items is fine.

When I attempt to add related artefacts, the modules on the page are generated as link to the blog, listing, date of publication, author, type. 

This has happened on other occasions with different pages. 

Besides this one issue, everything else is as specified.

**Comment by Floppy** [comment]
strange. That sounds like a separate issue (if it's happened before), can you open a new ticket and add a screenshot?
