### ISSUE TITLE
Remove Varnish from website

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#612]

**Comment by pezholio** [comment]
:bomb:

**Comment by Floppy** [comment]
Investigate the possibilities for removing it.

**Comment by pezholio** [comment]
So, while we're still struggling along with Varnish being enabled, this one-liner will DEFINITELY purge the Varnish cache:

```
sudo varnishadm -T 127.0.0.1:6082 -S /etc/varnish/secret ban.url .
```

**Comment by Floppy** [comment]
Problem found - we can work around nginx and varnish and disable expiry headers in the app, and we're golden.

Plan:

* [ ] Disable chef on node 2
* [ ] Change the application code to add our ghettofix from last night
* [ ] Re-enable chef on 1 and 3
* [ ] Put them into the pool and remove 2
* [ ] Bake for a few hours
* [ ] Move redirects into app/cloudflare that were handled by nginx
* [ ] check that cloudflare caching is working properly and not overloading the apps
* [ ] Re-enable node 2 and re-insert with the new configuration
