### ISSUE TITLE
Elasticsearch upgrade 0.19 -> 1.4

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#613]
Found are deprecating old elasticsearch versions, and our "rummager" search client is using 0.19. Needs to be brought up to using the 1.4 API.

**Comment by Floppy** [comment]
Found are deprecating everything below 1.4. Annoyingly, upstream rummager is updated from what we we are on (0.19) to 0.90, but not to 1.4. So, there is some work to do.

**Comment by Floppy** [comment]
See https://found.no/deprecation/

**Comment by Floppy** [comment]
Oh, god, rummager has its own rolled-in elasticsearch client.

**Comment by Floppy** [comment]
There are a lot of breaking changes in elasticsearch 1.0.0: https://www.found.no/foundation/elasticsearch-upgrade-guide/#breaking-changes

**Comment by pezholio** [comment]
:sob:

**Comment by Floppy** [comment]
We have until 1st July to get this done. We'll find someone to do it for us who knows elasticsearch.

**Comment by Floppy** [comment]
Jobs to do:

* [ ] Review and merge https://github.com/theodi/rummager/pull/10 to bring us up to date with alphagov and elasticsearch 0.90.
* [ ] Upgrade the code (probably mostly the client code under https://github.com/theodi/rummager/tree/master/lib/elasticsearch) to support elasticsearch 1.4
* [ ]  Contribute the upgraded code back to alphagov.

**Comment by Floppy** [comment]
We need to find someone with Elasticsearch and Ruby experience to do this efficiently. If you're looking at this and that sounds like you, contact james.smith@theodi.org.

**Comment by Floppy** [comment]
BREAKING: the rummager readme is out of date and they recently upgraded to 1.4: https://twitter.com/rjw1/status/600686977327996928

**Comment by Floppy** [comment]
This is very good news. It means we can come up to date with rummager and then we should be OK to change over. We can throw away the existing indexes without any problem, I think, so we can just make a new 1.4 DB and bin the old one.

**Comment by ajlanghorn** [comment]
Hello! I did the upgrade on the search stack from 0.9 to 1.4. Let me know if you have any queries.

**Comment by ajlanghorn** [comment]
Although since you've already found bob and Richard, I might not be.

**Comment by alext** [comment]
Part of the work involved in upgrading to ES 1.x involved reworking how the schemas were defined, specifically, we now have to record whether fields are multi-valued or not due to a change in the ES API.  See alphagov/rummager#369 for details of this.

**Comment by Floppy** [comment]
Hi @ajlanghorn - thanks for getting in touch! I suspect we'll be able to handle it ourselves by merging from your upstream repo, but if we have any issues, we'll give you guys a ping. Thanks :)

**Comment by Floppy** [comment]
As this is a merge job now that I'm sure we can handle ourselves, and we have a month to do it, I'm moving it to lowest priority.

**Comment by Floppy** [comment]
It could move out of this sprint if other things are more important.

**Comment by Floppy** [comment]
@alext ah, interesting, I guess we'll need to do the same. Thanks for the pointer :)

**Comment by rboulton** [comment]
Also of note - until very recently (perhaps a week ago), rummager was working fine on both elasticsearch 0.90 and 1.x.  We've recently started making use of features which don't exist in 0.90 (mostly in our schema definition layer so far), so I'm pretty sure it will no longer work with 0.90.  You may want to take this into account when upgrading, or may be fine to just jump all the way.

If you have specific difficulties, I'm happy to try and help, but am rather stretched for time at present.

**Comment by pikesley** [comment]
If you're at OpenTech, be sure we will track you down in order to buy you beer

**Comment by Floppy** [comment]
So, work is proceeding in https://github.com/theodi/rummager/pull/18. Most tests are now passing. Need to fix the next few tests and hopefully this should work. Plan is then to deploy rummager to Heroku and repoint the service to a new elasticsearch endpoint. No need to transfer the index, we can just rebuild it.

**Comment by pezholio** [comment]
I have all the tests passing, and have deployed rummager to Heroku to have a proper poke. However, I'm getting 403 errors when trying to connect. Have posted a support ticket [here](https://discuss.elastic.co/t/403-error-when-trying-to-connect/28672), but I've got as far as I can on this at the mo.

**Comment by pezholio** [comment]
So, we now have a Rummager instance at http://odi-rummager.herokuapp.com/. I've indexed a whole bunch of content from my local Quirkafleeg instance, and everything works. Next steps are:

- [ ] Checking everything works in content api
- [ ] Indexing the content from the live site
- [ ] Checking everything works in live
- [ ] Putting the search box back

Should be able to do all this tomorrow :smile:

**Comment by pezholio** [comment]
We now have a search!

http://theodi.org/search?q=taylor%20swift
