### ISSUE TITLE
Transfer ODI domains from DomainMonster to Gandi

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#614]

**Comment by Floppy** [comment]
@pikesley I nearly completed this, but then Gandi's website stopped responding. It doesn't look like the orders are in progress, so we can safely restart the process.

**Comment by pikesley** [comment]
It failed again, I'm tired of doing this wrong, can somebody else have a go please? https://www.gandi.net/admin/orders

**Comment by pezholio** [comment]
I'll have a crack

**Comment by pezholio** [comment]
Right, it says that the maximum number of days waiting for the owner to respond had elapsed, so I don't think you've done anything wrong. Do we need to hit them up again? I've relaunched the transfer again anyway.

**Comment by pezholio** [comment]
Who is the owner anyway? Is it Nigel?

**Comment by pikesley** [comment]
No, it's the Canadians. I think. @Floppy ?

**Comment by pezholio** [comment]
Hang on, yeah you're right. The DomainMonster thing threw me.

**Comment by Floppy** [comment]
which domains are we talking about here? I was just thinking of the ones on Nigel's 123-reg account.

**Comment by pezholio** [comment]
Superseded by #671
