### ISSUE TITLE
tweaks to the DaPaaS website

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#616]
Ideally 26/28 may. Half a day.

**Comment by ayymanduh** [comment]
@pezholio :)

* [ ] Change the website's landing page from static text to 'ODI boxes'
* [ ] Re-order the reports (chronological order)
* [ ] Minor SEO tweak on site to catch other spellings, e.g. dapas, dapass, dappass etc in the meta tags
* [ ] Split out the 'reports' page (currently under 'whats DaPaaS') into a new page 
* [ ] Check if google analytics are set up
* [ ] Change the structure of the related projects page (from static text to boxes)
* [ ] Figure out why when a new PDF report is uploaded, it doesn't display properly
* [ ] Fix the broken PDF for the factsheet
* [ ] Fix the broken PDF for D4.2

**Comment by pezholio** [comment]
@ayymanduh I get what you mean in point 1, but what sorts of content do you want in the boxes?

**Comment by ayymanduh** [comment]
@pezholio I'm not sure how this works, but we'd want it to be able to pull through the latest blogs, the 'what's dapaas?' page, the FAQ page, a link to the datagraft platform (live in July-ish), a box for our most recent event, etc.  The backgrounds could be the colours in Adrian's DaPaaS brand toolkit and we will add in images later.

**Comment by pezholio** [comment]
@ayymanduh Done a bit of background reading on SEO (ugh), and I don't think Google index meta keywords anymore, so point 3 might be a bit moot. Happy to do it though, as it's a two second job, but just so you're aware, it might not have the effect you want :smile:

**Comment by pezholio** [comment]
I've opened new tickets for the two remaining jobs (#644 and #645), so am going to close this.
