### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#617]
From @langphil: upcoming events overview. I've made http://theodi.org/event?edition=1&cache=1431941115 and would just like help fixing it. :) Give it time to load.

**Comment by Floppy** [comment]
We would like someone to turn this into a server-side page, for better searchability, accessibility and so on.

**Comment by langphil** [comment]
Entirely agree with your thoughts on things being server side. Thank you,
@floppy

—
*Phil Lang - Digital Production Editor*
@ODIHQ <https://twitter.com/ODIHQ> | thodi.org
@langphil <https://twitter.com/langphil> | *0741 44 63047*

**Comment by langphil** [comment]
Let me know if this is what you needed for this.

https://github.com/langphil/odievents-gh-pages

@gilesdring

**Comment by gilesdring** [comment]
Hi @langphil - thanks for that... Just need to confirm the requirement for this. Is it to be

1. a separate page to `/events`, although showing the same content (i.e. upcoming events of all types)
2. a separate page to `/events`, showing different content (i.e. courses only)
3. a replacement for `/events`

If it's a separate page, what's the best slug to give it: `/courses`? `/upcoming-events`?

**Comment by langphil** [comment]
Hi,

I’d like the following

1) I’d like to replace /events with a page that just lists upcoming events (not courses), meetups, lunchtime lectures, networking events, etc…

2) Each event module to show date, time, location, title of event, a booking link (goes to event page)

3) An aside bar to be present for related links

Happy to discuss this if you need more direction

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 11 June 2015 at 10:51:29, Giles Dring (notifications@github.com) wrote:

Hi @langphil - thanks for that... Just need to confirm the requirement for this. Is it to be

a separate page to /events, although showing the same content (i.e. upcoming events of all types)
a separate page to /events, showing different content (i.e. courses only)
a replacement for /events
If it's a separate page, what's the best slug to give it: /courses? /upcoming-events?

**Comment by gilesdring** [comment]
OK - wondering if there is a role for the "everything" page. At the moment, `/events` is the 'What's happening' top-level menu page. I could forsee adding `/events` as a sub of that, but renaming `/events` as `/whats-happening` or something. At the moment the `/events` page shows any upcoming events tagged `event` or `course_instance`.

**Comment by langphil** [comment]
If we could lose the course instance, that would be great. 

There is a separate issue / job in to do similar work on the upcoming courses page /courses. It needs to be moved server side. 

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 11 June 2015 at 11:12:29, Giles Dring (notifications@github.com) wrote:

OK - wondering if there is a role for the "everything" page. At the moment, /events is the 'What's happening' top-level menu page. I could forsee adding /events as a sub of that, but renaming /events as /whats-happening or something. At the moment the /events page shows any upcoming events tagged event or course_instance.

**Comment by gilesdring** [comment]
https://github.com/theodi/frontend-www/pull/384 raised to integrate changes.

Looks like this -->
![image](https://cloud.githubusercontent.com/assets/1731108/8112546/3d51faba-1060-11e5-98b3-518a30fdd715.png)

The content at the top and related elements come from the 'events' article.
The location is a `<p class="location">`, the Register is an `<a class="booking-url">`

**Comment by Floppy** [comment]
@langphil can you assess whether this is working as expected?

**Comment by langphil** [comment]
This is working as expected, the CSS does need styling. Can I discuss best way for me to do this. Thanks. 

I'll also need to see the live page to ensure that related artefacts are generating correctly.

**Comment by Floppy** [comment]
OK, let's have a quick chat in the morning about it.

**Comment by langphil** [comment]
Great, thanks James.

**Comment by Floppy** [comment]
So this is live at http://theodi.org/events already. Looks like we still need to:

* [ ] apply the CSS changes so we get an event list rather than the blocks.
* [ ] enable the related items in the sidebar.

**Comment by gilesdring** [comment]
Think related items are ready to go, just no content to show at the moment. Needs an article called _events_ to be created.

**Comment by Floppy** [comment]
Ah, great. @langphil , can you create an article called "events" and see if the right content gets pulled in?

**Comment by langphil** [comment]
I’ll create this now.

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 22 June 2015 at 09:11:04, James Smith (notifications@github.com) wrote:

Ah, great. @langphil , can you create an article called "events" and see if the right content gets pulled in?

**Comment by langphil** [comment]
I've created /events, but I am only getting this > theodi.org/events

**Comment by Floppy** [comment]
Hm, that's not right.

**Comment by langphil** [comment]
Something odd going on. The page was working for a bit, now it just "not found".

**Comment by gilesdring** [comment]
I noticed the not found issue. Here's a grab from /events in my local Publisher and Panopticon. It's possible that my /events page is not set up correctly, so the prod version has unmasked an issue.

Publisher -> [Editing Events | Publisher.pdf](https://github.com/theodi/shared/files/187/Editing.Events.Publisher.pdf)

Panopticon -> [Edit - Events | ODI Panopticon.pdf](https://github.com/theodi/shared/files/188/Edit.-.Events.ODI.Panopticon.pdf)

Hope this helps.

**Comment by langphil** [comment]
Hey, just looking to move this forward, I'm now getting a not found for the What's happening column in theodi.org nav. What's the best way to move this forward and allow me style the CSS on the page?

**Comment by Floppy** [comment]
Just looking into why it's 404ing. http://contentapi.theodi.org/events.json works OK...

**Comment by gilesdring** [comment]
FWIW, one of the related items is not available. http://contentapi.theodi.org/dapaas-about.json returns a 404. I suspect the code isn't handling this.

**Comment by Floppy** [comment]
Aha, that could be it - I didn't finish my investigations. Phil, can you remove that related item and see if it springs to life?

**Comment by gilesdring** [comment]
If it is the case, there should probably be some error handling included to reject related items that aren't available...

**Comment by gilesdring** [comment]
That code should either go here...

https://github.com/theodi/frontend-www/blob/master/lib/artefact_retriever.rb#L20

...or here...

https://github.com/theodi/frontend-www/blob/master/app/views/content/_related.erb#L5-L8

**Comment by langphil** [comment]
If we could put focus on completing this page as one of the first tasks tomorrow, that'd be great.

**Comment by gilesdring** [comment]
Yep. Will catch up with you just after 9. We have a plausible theory for the issue (see above)

**Comment by langphil** [comment]
Great, 

Let’s chat then.

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 7 July 2015 at 08:33:41, Giles Dring (notifications@github.com) wrote:

Yep. Will catch up with you just after 9. We have a plausible theory for the issue (see above)

**Comment by gilesdring** [comment]
@langphil I'm about - how's best to get in touch?

**Comment by Floppy** [comment]
I sent an invite to our Slack channel @gilesdring - did you get it?

**Comment by langphil** [comment]
Hey Giles, 

I’ll be in the tech team scrum. Let’s go from there. 

Also, you should have a slack invite.

I’ve a channel there called ‘theodi_website'

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 7 July 2015 at 09:15:37, Giles Dring (notifications@github.com) wrote:

@langphil I'm about - how's best to get in touch?
