### ISSUE TITLE
Discuss migration to Wordpress

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#619]

**Comment by Floppy** [comment]
@langphil can we have a chat about this sometime tomorrow or Thursday when convenient for you? Doesn't need long.

**Comment by langphil** [comment]
I'll find time in the calendar


—
*Phil Lang - Digital Production Editor*
@ODIHQ <https://twitter.com/ODIHQ> | thodi.org
@langphil <https://twitter.com/langphil> | *0741 44 63047*
