### ISSUE TITLE
Improvements to membership process

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#620]
Full details in https://docs.google.com/document/d/1hSK2vY7S5aQ6LE8LpO7-_gA4GclAEbao0GWU8TuHaKM/edit; needs breaking down

**Comment by JeniT** [comment]
Timebox until end of first week, including breaking down & estimating the tasks.

**Comment by pezholio** [comment]
The first three issues have fixes pending, and we've estimated the last two, so going to close this
