### ISSUE TITLE
2015 Dashboards

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#621]

**Comment by JeniT** [comment]
Maybe include #464

**Comment by Floppy** [comment]
Being done by @andylolz, me to support.

**Comment by Floppy** [comment]
Moved this to testing; I need to assess the state of play and work out how far we got.

**Comment by Floppy** [comment]
All done except the reach board, which I'll look at when I get time.

**Comment by Floppy** [comment]
Added new ticket just for reach board in #680
