### ISSUE TITLE
Send signup details straight to Capsule

### ISSUE THREAD

**Issue by pezholio** [theodi/shared#627]
Also, first and last names are getting mangled

**Comment by pezholio** [comment]
So, currently the situation goes like this:

* User signs up
* User details are sent to Chargify
* User details are sent to Xero (via [SignupProcessor](https://github.com/theodi/open-orgn-services/blob/047dff4454f20105341187577665b64565473d33/lib/signup/signup_processor.rb))
* We rely on third party Capsule / Xero sync to add the member to Capsule
* A job is queued to add details to Capsule (https://github.com/theodi/open-orgn-services/blob/047dff4454f20105341187577665b64565473d33/lib/capsulecrm/send_signup_to_capsule.rb)
* If the sync hasn't happened, it requeues

Presumably now, as we're not using Xero - we can cut the invoice creation out, and send all the necessaries straight to Capsule - @pkqk - does that sound correct?

**Comment by pkqk** [comment]
@pezholio yep. I would cut out the entire Xero step. There is enough info from the Chargify signup to populate Capsule.

As long as if necessary the Xero integration can also happen.

**Comment by Floppy** [comment]
We'd just need to be sure that Xero will still make the link to the capsule data. I think it will, but I'm not 100%. It's flaky as hell though anyway, as it assumes things like UNIQUE NAMES. (sigh)

**Comment by pezholio** [comment]
Do we even need to make the link between Xero and Capsule, as we're using Chargify now?

**Comment by Floppy** [comment]
Mm, I don't know what Chargify does, but I know that link allows people to see unpaid invoices in Capsule... I'm not sure. @greenreveller might know best.

**Comment by pkqk** [comment]
There should be no "unpaid" from chargify as it's :credit_card: only

**Comment by JeniT** [comment]
Please check with finance (Alison) about whether they need to see information about the paid invoices in Xero. They might need something like that for tracking purposes.

**Comment by Floppy** [comment]
Good plan; @alisonwalters, any thoughts?

**Comment by pezholio** [comment]
We can probably keep this in and remove the Capsule / Xero integration anyway if it causes any problems. The issue seems to be that the integration isn't working properly, and email addresses aren't getting copied over to Capsule.

**Comment by pezholio** [comment]
Right, so, the issue we have is that some contacts exist already in Capsule - if they sign up with a different email (i.e. we've contacted them via their work email, and they sign up with their personal email) then the link is created against that contact in Capsule, and when SignupProcesser runs, they never get found in Capsule because we key on email.

There are therefore a few options here:

* We search by the person's name, rather than email - Capsule keys on person name anyway, so this assumption matches up with how the Xero / Capsule integration works. This falls down when we have people with the same name though.
* We do away with the auto integration, and roll our own; or
* When we create the contacts in Xero, we add the membership ID in brackets, so all names are unique

The first option is the quickest and dirtiest, but will probably bite us in the ass further down the line, and the third option seems like a bit of a cheat, but would definitely work. The second option is the neatest, but might take a couple of days, and may end up being superseded once we stop raising invoices in Xero.

Any thoughts?

**Comment by alisonwalters** [comment]
Hi,
Sorry I'm working on some urgent finance deadlines just given to me by
Louise. I will anseer as soon as I can

Ali

**Comment by pezholio** [comment]
Hey Alison, I think we're going to keep the Xero situation as it is for now :smile:

**Comment by pezholio** [comment]
Tagging @greenreveller in this conversation

**Comment by greenreveller** [comment]
As discussed, I'm for the second option (e.g. doing away with auto integration and creating our own system) as it will also solve the 'convert to person' problem with individual Supporters. Aware that this may mean needing to merge capsule entries where a person already has an entry. 

And just to check - in the instance where someone has an entry in capsule and signs up using the SAME email this will work fine? (it does at the moment but just want to verify how this new approach would work). Would a new entry be created on would membership be added to an existing Capsule entry?
