### ISSUE TITLE
Startups page

### ISSUE THREAD

**Issue by langphil** [theodi/shared#628]
I was wondering if there is any chance that the aside could be turned on for related items on (/start-ups)?

[Link](http://www.theodi.org/start-ups)
This is being requested as the page needs to go live for the launch of the new startups. 

@floppy @pezholio

**Comment by Floppy** [comment]
aside as in related articles? That shouldn't take but a moment now. Sorry we have to do it time and again, the codebase has far too much repetition in it :(

**Comment by langphil** [comment]
Yes, aside as in related articles. 

Thanks @floppy. 

That's OK, no worries.

**Comment by Floppy** [comment]
Should be able to do it after this meeting, unless @pezholio gets there before me. It's pretty much just a partial include these days.

**Comment by langphil** [comment]
Happy to be shown how this is achieved, if it makes sense.


—
*Phil Lang - Digital Production Editor*
@ODIHQ <https://twitter.com/ODIHQ> | thodi.org
@langphil <https://twitter.com/langphil> | *0741 44 63047*

**Comment by Floppy** [comment]
Nah, it's best if we do it so we can check it locally first. Could introduce errors, so you'd need a running local system. Shouldn't take a minute or two.

**Comment by langphil** [comment]
Just checking the status of this.
