### ISSUE TITLE
Change to unicorn

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#638]
thin is terrible

**Comment by pkqk** [comment]
theodi/open-data-certificate#1033

It's currently possible for a few long running queries (which are very easy to trigger in certificates at the moment :cry:) to stop all the servers responding.

It might be worth trying
  - `config.threadsafe!` (I'm not sure if you need to remove `Rack::Lock` from the middleware in that case)
  - `unicorn` - though this appears to be designed for fast connections and probably smaller response sizes
  - `puma` another concurrent rack server
  - `passenger`

**Comment by dicknorris** [comment]
Book to  ODM  > WP3 > Task 3.5

**Comment by quadrophobiac** [comment]
This issue was moved to theodi/open-data-certificate#1536
