### ISSUE TITLE
Provide for invoicing of new members

### ISSUE THREAD

**Issue by JeniT** [theodi/shared#641]
See theodi/member-directory#413

**Comment by Floppy** [comment]
This looks like it's still in progress, but is marked as done here. Is there still stuff to do? This is the only membership work in the current sprint, so if there's anything outstanding this should still be open. @pezholio @greenreveller can you update the current state here as you see it?

**Comment by greenreveller** [comment]
There is a related ticket #418 re automating membership/Summit ticket sales. I believed that this was also in this sprint as Stuart, Alison and I met early last week to discuss how to proceed with how summit ticket sales were going to work with the member directory. All detail is in the ticket. We need to know whether we can use a CSV exported from Eventbrite to create a script which will automatically sign up people who have bought summit tickets + membership as members (or do we need to do each one manually)

**Comment by Floppy** [comment]
Assuming that's referring to theodi/member-directory#418

**Comment by Floppy** [comment]
That wasn't linked to this ticket and I don't see it linked elsewhere from sprint planning. @pezholio, was it included in the plan?

**Comment by pezholio** [comment]
No, the automation wasn't planned for. Was hoping to get it in for next sprint.

**Comment by greenreveller** [comment]
Ah ok - can we prioritise for the next sprint? We need to get this process agreed before we can launch summit ticket. Apologies if I got the wrong end of the stick on what was being covered this sprint and not. Could you share me the link with huboard (spelling?) so I can keep up to speed with what's in the sprint plan?

**Comment by Floppy** [comment]
Here you go: https://huboard.com/theodi/shared#/

**Comment by Floppy** [comment]
What's the deadline for summit ticket launch @greenreveller? Apologies for any confusion from our end as well.

**Comment by greenreveller** [comment]
Thanks both. Deadline = beginning of week 29 June (nb offsite next week)

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002
