### ISSUE TITLE
Fix broken report uploads

### ISSUE THREAD

**Issue by pezholio** [theodi/shared#645]
See #616. Seems to be a flickering state. Sometimes works, sometimes doesn't.

**Comment by Floppy** [comment]
Will see if @gilesdring can take a look into this.

**Comment by Floppy** [comment]
@ayymanduh can you try to describe the PDF upload problem (preferably with steps to reproduce it) so that @gilesdring can maybe take a quick look?

**Comment by ayymanduh** [comment]
Sure. So when you upload a report to DaPaaS, either the PDF document doesn't save, or eventually it does but then won't actually load.  See D4.2 (http://project.dapaas.eu/dapaas-reports) as an example. @gilesdring @Floppy

**Comment by Floppy** [comment]
Can you list the sequence of actions for uploading a report? Just so we know we're testing the right thing?

**Comment by ayymanduh** [comment]
Publisher > add artefact > (select kind) report > upload PDF.

**Comment by Floppy** [comment]
Thanks! :dancer:
