### ISSUE TITLE
SEO / Metadata implementation

### ISSUE THREAD

**Issue by langphil** [theodi/shared#647]
**User story:**

1) As a producer I would like to enter relevant metadata into Publisher during the publishing process.
2) As a producer I would like this metadata to integrate nicely with the following: Facebook Open Graph, Twitter Cards, Google, anything else of relevance (discuss).
3) Implement [Google Tag Manager](http://www.google.com/tagmanager/) < let's chat about this.

**Comment by gilesdring** [comment]
Design work being documented in https://github.com/theodi/shared/wiki/SEO-metadata

**Comment by gilesdring** [comment]
Fixed by 
* theodi/frontend-www#397
* theodi/frontend-www#398
* theodi/frontend-www#399
* theodi/frontend-www#400
* theodi/frontend-www#401

**Comment by gilesdring** [comment]
There are still some outstanding issues related to images. These are raised as separate issues.
