### ISSUE TITLE
Bypassing the 2nd pair of eyes process on "new editions" of artefacts

### ISSUE THREAD

**Issue by langphil** [theodi/shared#653]
**User story:**

1) As a writer / publisher for theodi.org I would like to have the ability to make swift edits to content on already published on theodi.org, without having to send the item for a 2nd pair of eyes edit. I would like to bypass this process, to create new editions, edit them and publish them as a single user.

**Comment by gilesdring** [comment]
Should there be limitations on the types of changes that can be made without second pair of eyes?

**Comment by langphil** [comment]
As the ability to publish is limited to three individuals at the ODI, I would say no limitations please. 

These three individuals, should be granted the ability to ‘Create new editions’, ‘Send to 2nd pair of eyes’, ‘OK for publication’ and ‘Publish’

Permissions are currently managed in the Admin tasks section of signon.theodi.org

The majority of these changes made will be;

* Title
* Description
* Tags
* Body copy
* Event relevant details (date, location, time)



-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 9 July 2015 at 11:30:10, Giles Dring (notifications@github.com) wrote:

Should there be limitations on the types of changes that can be made without second pair of eyes?
