### ISSUE TITLE
Sell membership with summit tickets

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#656]
See https://github.com/theodi/member-directory/issues/418

Added to planning board for sprint 49. /cc @greenreveller

**Comment by pezholio** [comment]
The plumbing is in place for this, just waiting for confirmation from @greenreveller about what the membership tickets will be called

**Comment by pezholio** [comment]
PR is here for reference because Huboard doesn't show related PRs https://github.com/theodi/open-orgn-services/pull/439

**Comment by greenreveller** [comment]
Hi @pezholio, @langphil has added the ticket types to Eventbrite page. 
I've pasted the categories and ticket names in this doc: https://docs.google.com/document/d/1k19Cavfabq6cZZDrh6iB7vJsPJT487qe4ZbYn2Coh6Q/edit

Is that what you need?

If you need to login to Eventbrite: https://www.eventbrite.co.uk/myevents/?internal_ref=login
Login details: events@theodi.org PW: openevents2012

**Comment by Floppy** [comment]
yoink

**Comment by pezholio** [comment]
^ Is that a "I'll take this from here" type yoink?

**Comment by greenreveller** [comment]
Hi Stuart, Keren is just going to double check the categories so if you can hold off for 20 mins or so I will let you know when we get the final green light

**Comment by pezholio** [comment]
Cool, no worries

**Comment by greenreveller** [comment]
Heya, doc now updated. Tickets with membership are highlighted in yellow. Cheers

**Comment by greenreveller** [comment]
also... high baby alert!!! eeeeeeeeee :)

**Comment by pezholio** [comment]
:baby: :baby_bottle:

**Comment by pezholio** [comment]
@greenreveller Am I right in thinking that the SME and corporate packages come with supporter membership included?

**Comment by pezholio** [comment]
And the individual supporter packages come with individual membership, natch

**Comment by greenreveller** [comment]
Thanks Stuart - meant to say that the packages highlighted in yellow in the
doc are the ones which are summit + membership (so 3 out of the 6 packages)
https://docs.google.com/document/d/1k19Cavfabq6cZZDrh6iB7vJsPJT487qe4ZbYn2Coh6Q/edit

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002
