### ISSUE TITLE
Set up Ben C's laptop

### ISSUE THREAD

**Issue by pikesley** [theodi/shared#662]
Things we will need to do:

- [x] Install Xcode
- [x] Configure rbenv
- [x] Set up SSH keys (for Github)

**Comment by Floppy** [comment]
Also notes for possible boxen:
* [ ] Install slack client
* [ ] Install Atom?

**Comment by Floppy** [comment]
* [ ] IRC client?

**Comment by Floppy** [comment]
* [ ] phantomjs
