### ISSUE TITLE
Events page - Related items returns an internal error on /events

### ISSUE THREAD

**Issue by langphil** [theodi/shared#669]
Related items added in Panopticon returns an internal error on /events

**Comment by Floppy** [comment]
This seems to be a more general issue, I've seen this on a number of related items recently. They seem to throw 404s somewhere, which then makes the entire page appear as a 404.

**Comment by gilesdring** [comment]
Will look at this as matter of urgency today. If there's a clean pattern for dealing with it, will document here.

**Comment by gilesdring** [comment]
Think this is no longer an issue on the basis of changes made to rendering code in https://github.com/theodi/frontend-www/commit/0c853a312a2d1f50e7a101c5173f2161617ad937.

**Comment by gilesdring** [comment]
@Floppy Let me know if there are other instances of this.

**Comment by Floppy** [comment]
We were seeing this in jobs as well.

**Comment by gilesdring** [comment]
OK - so the 'fix' to this in the `/events` page context is that I no longer rely on `ArtefactRetriever.new(content_api, Rails.logger, statsd).fetch_artefact(related['slug'])` (which was called in the `content/_related.html.erb` template). Instead, I get everything I need from `related_links` action defined in `app/presenters/publication_presenter.rb`, which is fine for this requirement.

**Comment by gilesdring** [comment]
If you can point me at the jobs, I'll take a look see if there is a similar issue. I think the ultimate fix ought to be (per [these comments](https://github.com/theodi/shared/issues/617#issuecomment-117270812)) to return something sensible in the event there is a 404.
