### ISSUE TITLE
Transfer ownership of opendatainstitute.org

### ISSUE THREAD

**Issue by pezholio** [theodi/shared#678]

**Comment by Floppy** [comment]
@floppy will work out who we actually need to talk to and what we need.

**Comment by gilesdring** [comment]
Thoughts on this one: there's an infrastructure answer (wherever the domain name is registered register an HTTP redirect), and a software answer (catch requests made to opendatainstitute.org, and respond with a redirect). Presume this is not news, but thought it useful to summarise.

**Comment by gilesdring** [comment]
opendatainstutute.org is registered at Hover. If this is true... https://help.hover.com/entries/21196383-How-to-Forward-your-domain-name might work.

**Comment by Floppy** [comment]
yeah - we're having repeated problems getting enough control over the domain to do the infrastructure answer, so the software answer is an interim solution so that the problem goes away while we get the proper fix in place.

**Comment by gilesdring** [comment]
OK - Figures.

**Comment by gilesdring** [comment]
Same true of static, contentapi, etc subdomains?

**Comment by Floppy** [comment]
I think as long as we redirect in the frontend app, the rest should be fine.

**Comment by Floppy** [comment]
So we've handled this with a redirect, and I'll take the contact about domain transfer onto my non-tech todo list. The tech infrastructure work will come back if we ever manage to make that transfer happen successfully.

**Comment by gilesdring** [comment]
As long as you know who owns the domain, and you trust them to not stand up a mirror ODI site from your public code, you're fine ;-)
