### ISSUE TITLE
Discussion and action: What can we do about http://opendatainstitute.org?

### ISSUE THREAD

**Issue by langphil** [theodi/shared#681]
Issue - If you search for Open Data Institute on Google you end up at:

http://opendatainstitute.org

or at least, I do. I'm assuming it's pointing to the same site as:

http://theodi.org

I'm pretty sure that this is bad for SEO as it's duplicate content under different URLs. My understanding is that best practice is to redirect URLs to the main URL for the site, so:

http://opendatainstitute.org > http://theodi.org

Can we discuss this and work out what sort of action it needs.

**Comment by Floppy** [comment]
We've tried to deal with this before in #678, but the transfer never bloody works. We will try again, as you're absolutely right, this is totally wrong.

**Comment by langphil** [comment]
Don't need this to be directly dealt with now. Just adding it in to add to the list.

**Comment by gilesdring** [comment]
`dig` results:

    opendatainstitute.org.		900	IN	A	5.79.36.124
    www.opendatainstitute.org.	900	IN	A	5.79.36.124

    theodi.org.  		146	IN	A	141.101.126.200
    theodi.org.  		146	IN	A	141.101.125.200
    www.theodi.org.		266	IN	A	141.101.125.200
    www.theodi.org.		266	IN	A	141.101.126.200

So the `opendatainstitute.org` points directly to Rackspace, and `theodi.org` points at Cloudflare.

See also comments on #678

**Comment by gilesdring** [comment]
There's now a fix in for this. See #678

**Comment by Floppy** [comment]
The redirect fix works for now, and it's on my list to get the transfer properly done with the owners finally. So, closing this as no tech work required for now.
