### ISSUE TITLE
Vendor Surveyor

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#685]
Vendor surveyor into ODC so that it's possible to refactor and improve it.

**Comment by pkqk** [comment]
part of #636

**Comment by pezholio** [comment]
Is this ready to move to done now?

**Comment by pkqk** [comment]
Yeah, just needs merging then can be marked as done

**Comment by pezholio** [comment]
It's moiged I think?

**Comment by pkqk** [comment]
yep, I hadn't checked yet.
