### ISSUE TITLE
Update DataKitten metadata capabilities

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#688]

**Comment by danielgavrilov** [comment]
Updating according to **documentationMetadata** in the [Google doc](https://docs.google.com/document/d/1XhnKyzXlQRF2gFsSi69vVJ9Q1jJggtUWl73iYq2NS14/edit#heading=h.fuy5mj7x5uln). Fields to update:

- [X] description
- [X] update_frequency
- [X] identifier
- [X] landing_page
- [X] temporal
- [ ] spatial
- [X] theme

**Comment by danielgavrilov** [comment]
I haven't implemented `spatial` as I'm not sure what would be a good way to store it. The most common way it's stored on CKAN sites is a "bounding box" (north & south latitude + west & east longitude), but data.gov also stores GeoJSON polygons. 

I'm happy to merge what I have so far until this is decided?

**Comment by Floppy** [comment]
@danielgavrilov @pezholio to discuss spatial requirements and move this forward.

**Comment by dicknorris** [comment]
Book to ODM > WP3 > Task 3.5
