### ISSUE TITLE
Flowchart legal section bug

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#690]

**Comment by quadrophobiac** [comment]
Currently the 'Legal' pathway terminates prematurely (redirects to end) for the paths **'Have you carried out a Privacy Impact Assessment'** `answer = TRUE`,

"Where is your Privacy Impact Assessment published?"  
"Where is the privacy notice for individuals affected by your data?"  
"Is there someone in your organisation who is responsible for data protection?"  
"Has your anonymisation approach been independently audited? "
and  
**'Are you required or permitted by law to publish this data about individuals?'** `answer = TRUE`  
for
"Where is your Privacy Impact Assessment published?"  
"Where is the privacy notice for individuals affected by your data?"  
"Is there someone in your organisation who is responsible for data protection?"

**Comment by quadrophobiac** [comment]
The practical parthway terminates without an 'END' block

**Comment by bcouston** [comment]
Made an issue in open-data-certificate https://github.com/theodi/open-data-certificate/issues/1216

**Comment by bcouston** [comment]
'END' block now displays and all questions display except for one (id="thirdPartyOrigin"). This is the result of a nested if (multiple dependencies) rather than the reasons described in https://github.com/theodi/open-data-certificate/issues/1216.

**Comment by pezholio** [comment]
It's worse than that. We're missing an entire chunk :cry: - namely this whole section:

https://github.com/theodi/open-data-certificate/blob/staging/prototype/jurisdictions/certificate.GB.xml#L70-L119
