### ISSUE TITLE
Tests for flowchart

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#691]

**Comment by Floppy** [comment]
And refactor

**Comment by quadrophobiac** [comment]
extract the ```ruby @deps.reverse.join("\r\n").gsub("’", "'") ``` logic from the controller and show template into a helper

**Comment by Floppy** [comment]
Sounds sensible. A lot of the work is being done in various partials, which we could test individually perhaps as well.

**Comment by bcouston** [comment]
I have made a separate issue for the missing questions in the Legal flowchart (#1216). As of now a solution to the missing "End" block in practical has been fixed and implemented. Pull request describing all changes: #1209

**Comment by bcouston** [comment]
Made an issue concerning moving the source of the flowcharts from a certificate .xml to the Survey model as already done for the questionnaire itself. Search for #1217 in open-date-certificate repository.

**Comment by bcouston** [comment]
@pezholio is happy with the amount of tests @quadrophobiac and I have written so far, currently working on fixing erroneous tests.

**Comment by bcouston** [comment]
Cucumber scenario is too brittle to test helper with the new features so a separate unit test suite is being written.

**Comment by quadrophobiac** [comment]
Basic unit tests were written for flowchart controller and flowchart model, but advise that halting production of tests until a review of the tests already in place for modelling the XML in ruby (see below) is completed to avoid duplication of work
(Test suites exist in)
```
vendor/surveyor/gems/surveyor-1.4.0/spec/
test/unit/question_test.rb
test/unit/response_set_test.rb
```

**Comment by quadrophobiac** [comment]
Ticket raised here https://github.com/theodi/shared/issues/697 may be the appropriate place to transfer the decision making to

**Comment by Floppy** [comment]
Waiting for resolution of #698 as it may affect these tests.
