### ISSUE TITLE
Review UD2D deliverables and provide feedback

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#699]
There are a number of draft deliverables for Urban Data 2 Decide, which we need to review and comment on.

**Comment by JeniT** [comment]
@floppy will organise a workshop

**Comment by pezholio** [comment]
I've had a look and given feedback on 3.1.0.1 now - is this the extent of this task?

**Comment by dicknorris** [comment]
Book against UD2D > WP3 Methods and Modelling > Task 3.1 / 3.2
