### ISSUE TITLE
Recommend tools and technologies for making open data visualisations (UD2D)

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#702]

**Comment by JeniT** [comment]
see https://github.com/theodi/open-data-tech-review/wiki#visualisation-tools

**Comment by JeniT** [comment]
See also https://hackpad.com/Tools-for-the-Open-Data-Challenge-Series-aCK0hgumz00#:h=Data-Analysis-+-Visualisation

**Comment by JeniT** [comment]
maybe talk to @ayymanduh about tool lists pulled together for ODM

**Comment by ayymanduh** [comment]
List for ODM is here (http://project.opendatamonitor.eu/wp-content/uploads/deliverable/OpenDataMonitor_611988_D2.3-Best-practice-visualisation,-dashboard-and-key-figures-report.pdf) [p.30 onwards] @quadrophobiac

**Comment by quadrophobiac** [comment]
latest additions to the growing list here https://docs.google.com/document/d/1OTZB-Vzwi9ohRvzqsBArNN19O4VGGoJ6ejZKYyfYAGs/edit#heading=h.lctr6k9bvy7a

**Comment by quadrophobiac** [comment]
@dicknorris @JeniT - is the workshop for next week the date by which you'd like this list compiled? I'm getting there but if the deadline isn't immediate then it'd be useful to proceed incrementally on it

**Comment by dicknorris** [comment]
Book to UD2D > WP3 > Task 3.1
