### ISSUE TITLE
Add a DaPaaS logo onto the CSV lint about page

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#708]

**Comment by dicknorris** [comment]
Book to  DaPaaS  > WP1 > Task1.2

**Comment by Floppy** [comment]
@ayymanduh we're waiting for the text and logo from you on this. Can you pop it in here? Ta :)

**Comment by ayymanduh** [comment]
Logo attached. What do you need text wise? 
![dapaas - logo multi xlarge](https://cloud.githubusercontent.com/assets/6029876/9441711/a49c77e2-4a6f-11e5-8385-9125045574e8.jpg)

**Comment by Floppy** [comment]
@ayymanduh wondering if there's some proper "supported by" type text we should add. Maybe we should just link to http://project.dapaas.eu/ and include something like:

"Development of this tool was partly supported by the DaPaaS project, co-funded by the European Commission under the Seventh Framework Programme (FP7 2007-2013)"

How's that sound?

**Comment by bcouston** [comment]
@dicknorris @Floppy How large should the logo be and how should it be positioned in the page?

**Comment by bcouston** [comment]
![screen shot 2015-08-27 at 14 55 25](https://cloud.githubusercontent.com/assets/9949074/9522259/ca46e4a6-4ccb-11e5-8479-6718a26a56ac.png)

**Comment by ayymanduh** [comment]
Looks perfect to me, thanks all!
