### ISSUE TITLE
Test and review the DataGraft (by DaPaaS) platform and its tools.

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#709]
The technical partners on the project have been working on the DaPaaS platform.  They have asked us to test it and provide feedback.  These will be ready to view by 1st September.

**Comment by dicknorris** [comment]
The technical partners on the project have been working on the DaPaaS platform.  They have asked us to test it and provide feedback.  These will be ready to view by 1st September.

**Comment by dicknorris** [comment]
Book to  DaPaaS > WP1 > Task 1.2

**Comment by Floppy** [comment]
@ayymanduh can you provide more detail on what we need to do here please?

**Comment by ayymanduh** [comment]
Testing the DataGraft (https://datagraft.net/) platform. Any bugs/errors can be reported (via Github, yay!) at: https://github.com/dapaas/datagraft/issues/new 

Work to include:

1. Uploading files 
2. Testing the transformation tools
3. Testing the hosting functionality
4. Reviewing the documentation (https://datagraft.net/documentation/)
5. Testing the API (https://datagraft.net/api/)
6. Sense checking the FAQ (https://datagraft.net/faq/)
7. Outputs = blog post to write up what we've learnt.
7a. Write a CSV Lint blog post (as developments funded by the DaPaaS project)

**Comment by bcouston** [comment]
As @quadrophobiac is off for the rest of this week, perhaps I can assign this to myself? I have a bit of a background in QA

**Comment by ayymanduh** [comment]
@bcouston that would be great, thank you. We have two days allocated for this from budget. Can you set aside tomorrow (Fri 4th)?

**Comment by bcouston** [comment]
@ayymanduh Yes, although I may have time this afternoon to start if that's okay?

**Comment by quadrophobiac** [comment]
@ayymanduh state of play on this after myself and @bcouston worked on it is as follows. I have questions where some of the feedback should be stored, raised in bold below - could you advise

- [x] Uploading files *issue tickets raised*
- [x] Testing the transformation tools *issue tickets raised*
- [x] Testing the hosting functionality *issue tickets raised*, **ALSO have suggestions doc on UX of workflow, where to relay?**
- [x] Reviewing the documentation (https://datagraft.net/documentation/) **have written suggestions on legibility, where to relay?**
- [x] Reviewing the 'how it works' videos (on the landing page, scroll down: https://datagraft.net/) **have written suggestions on legibility, where to relay?**
- [ ] Testing the API (https://datagraft.net/api/)   
> On a read through my impression is that it's a pleasing and legible API, however the real test of the API would be (a) someone using it (b) someone with linked data experience giving the linked data portions of the API an eyeball
- [x] Sense checking the FAQ (https://datagraft.net/faq/) **have written suggestions on legibility**
- [ ] Sense checking the terms/privacy documents **pending complete but same question as to where the feedback should be stored/relayed applies here**

**Comment by ayymanduh** [comment]
Thank you @quadrophobiac & @bcouston.

If the feedback/questions are suitable for email, can they please be sent to the DaPaaS project team? Group email is: <dapaas@googlegroups.com>

**Comment by bcouston** [comment]
Writing a blog post about DataGraft to be completed
