### ISSUE TITLE
Handle large CSV file sizes for upload

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#710]
We can't validate anything over 700k in a file upload without causing an error (see https://github.com/theodi/csvlint/issues/201). It's unclear whether this is because of the nginx file upload size limit, or something in the app instead.

We want: 
* validation of web-hosted CSVs of any size
* validation of uploaded files of up to 100MB size

* [x] Work out where the bottleneck is
* [x] Increase the nginx file size limit *anyway* to 100M (see https://github.com/theodi/csvlint/issues/201)
* [x] Make sure that the app can handle those file sizes (locally, without nginx involved). See https://github.com/theodi/csvlint/issues/213 for possible thoughts on how this could be achieved in a user-friendly way.

**Comment by Floppy** [comment]
@bcouston and @quadrophobiac are going to take a look at this to see if we can make some progress before CSVlint is used for the DaPaaS workshops next week, or at least isolate the problem further.

**Comment by bcouston** [comment]
@Floppy This might be server side, locally I can validate a 1.2MB csv file (http://training.theodi.org/resources/dataset2.csv), on live, 413 entity too large error with an infinite validation loop.

**Comment by bcouston** [comment]
On the local side, Mongo can't store files larger than 16MB, investigating into using a package that splits data into chunks (http://www.resumablejs.com/) or GridFS.

**Comment by bcouston** [comment]
![screen shot 2015-08-21 at 14 09 52](https://cloud.githubusercontent.com/assets/9949074/9409081/a8f97fcc-480f-11e5-99ef-cb05fd7f34e3.png)

**Comment by dicknorris** [comment]
Book to DaPaaS > WP1 > Task 1.2

**Comment by Floppy** [comment]
The server-side and investigative stuff here is OK, and the next thing is to look at how we make a better upload experience for people using a javascript uploader like ResumableJS.
