### ISSUE TITLE
Transfer ODC live to new cookware

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#711]

**Comment by pikesley** [comment]
New nodes seem to work (against a copy of the current prod DB). We should do like this:

* Quiesce Chef on the current nodes
* Move the CURRENT tag to whatever STAGING currently is
* Bring up new nodes with CURRENT
  * against the current DB - this will run migrations, but they are fairly benign
* Swap new nodes in and old nodes out on load-balancer
* Kill the old nodes

although I'm aware that @pkqk has Opinions around how we're using tags. Let's discuss tomorrow before we start
