### ISSUE TITLE
Investigate CSV streaming validation

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#712]
Look at how we could get CSVlint to validate in a streaming fashion rather than a entire-file-at-once way. This would help when dealing with big files off the web, and perhaps also for uploads.

**Comment by quadrophobiac** [comment]
#### The problem being solved
we would like to be able to validate CSVs in a manner where execution control is not surrendered completely to the validators `parse_csv` method. A better solution would be for the parse_csv method to proceed in a **stateful** **non-blocking** manner, for instance by refactoring the `parse_csv` (and attendant methods) to a separate class. This class could be **polled** by the validator object which invokes/initialises it and its parsing methods.
The changes will be made at the level of csvlint gem, without availing of threading, as it is imagined that this will be handled at a higher stage, for instance within the CSVlint rails app

@Floppy can you review whether I have articulated the problem correctly above

**Comment by quadrophobiac** [comment]
Consultation with @pkqk on (28/09/2015) has helped deduce a straightforward way of employing Ruby's CSV library to handle the streaming

**Comment by quadrophobiac** [comment]
- [ X ] refactor CSV parsing methods from Validator class to a separate class
- [  ] Use CSV libraries existing streaming abilities
- [ ] Adjust Gem Test Suite and test against rails app at each change

**Comment by quadrophobiac** [comment]
Have reviewed the CSV library more thoroughly and it appears that the previous parsing code was also CPU bound rather than IO Bound. The IO blocking method for that library is CSV.read() rather than CSV.new(). As such not sure if the work done to date is necessary :-1:

**Comment by quadrophobiac** [comment]
this ticket related: https://github.com/theodi/csvlint.rb/issues/122

**Comment by Floppy** [comment]
Thanks. We'll go over this in sprint planning and break it down.

**Comment by Floppy** [comment]
@pezholio can you go through Stephen's findings with him and help him work out how to proceed?
