### ISSUE TITLE
Javascript uploader for CSVlint

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#713]
Use a better browser upload solution, perhaps resumable.js or something similar.

**Comment by pezholio** [comment]
See https://github.com/theodi/csvlint/issues/216

**Comment by bcouston** [comment]
Suggestions: Implement this for uploading schema files as well

**Comment by quadrophobiac** [comment]
recapitulating the points raised in prior tickets as summary of the objective of this ticket:

we want to implement resumableJS (or some interface to the HTML5 file upload API) to allow a means of uploading a file that has better tolerance for connection failures or other interruptions to the file being uploaded

**Comment by pezholio** [comment]
I think this is good to go now - there was a bit of fiddling around with tempfiles and the like, but we're now saving chunks to GridFS, which is much nicer.
