### ISSUE TITLE
Investigate open data tools

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#718]
Investigate these tools; see what they do, how they fit into the larger scheme of things, and write up the reviews as a blog post.

* [ ] Scraperwiki's Databaker
* [ ] [18F's open-data-maker](http://github.com/18f/open-data-maker)

**Comment by bcouston** [comment]
I've investigated the open data maker a bit, data dictionary feature seems useful (defined in the data.yml file) and provides an effective way of querying/filtering the data via json API. At the moment I think the scope of the project is only for already stored csvs for security purposes. Other than that just installing a lot of dependencies to get it working.
