### ISSUE TITLE
Run a bash wizardry hour

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#732]
Many of the interns (and others no doubt) would like a bit of bash knowledge dropped on them. @pikesley, can you do an hour or so just going through the basics, and some of the more advanced possibilities?

**Comment by pezholio** [comment]
Count me in on this. I just muddle along and pretend I know what I'm doing. Could do with having some advanced knowledge dropped on me.

**Comment by quadrophobiac** [comment]
a walkthrough of some of your most employed bash scripts within the ODIs current code base would be instructive
Best practices of when to use bash and when to seek an alternative (hammer / nails etc.)

**Comment by mattwagstaff** [comment]
Can anyone get in on this? Would love to increase my knowledge here.
