### ISSUE TITLE
Migrate services-manager to new infra

### ISSUE THREAD

**Issue by pikesley** [theodi/shared#738]

**Comment by pikesley** [comment]
The new node is up with a new queue, seems fine

Remaining tasks:

- [ ] Kill old node
- [ ] Terminate old redis box?

**Comment by pikesley** [comment]
I have made a traumatic discovery. On the Redis server:

    netstat -pan | grep redis | grep ESTAB | tr -s ' ' ' ' | cut -d ' ' -f 5 | cut -d ':' -f 1 | sort | uniq
    162.13.15.59
    37.188.117.9
    5.79.7.112

And then

    for ip in 162.13.15.59 37.188.117.9 5.79.7.112 ; do knife search -a FQDN "ipaddress:${ip}" ; done
    1 items found

    backend-quirkafleeg-03:
      FQDN:

    1 items found

    backend-quirkafleeg-02:
      FQDN:

    1 items found

    backend-quirkafleeg-01:
      FQDN:

(ignore that fact that I don't know how to work `knife search` properly)

THE BACKEND NODES STILL SPEAK TO THIS REDIS!

**Comment by pezholio** [comment]
That's no **huge** drama. They don't store state, so we can flip over quite
easily
