### ISSUE TITLE
Fix CSV Lint bugs, identified by UK Data Service

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#740]
UK Data Service have identified two bugs when using CSV Lint:
(1) The descriptive text when adding a file needs updating.  
(2) They have encountered an error when downloading the standardised file

Acceptance criteria:

**Comment by quadrophobiac** [comment]
(1) is a cosmetic change: https://github.com/theodi/csvlint/pull/226
(2) it looks like the error encountered was a `Mongoid::Errors::DocumentNotFound in ValidationController#show` caused by the link presented on 'Download Standard CSV'  providing an ID that didn't match with persisted data, investigating what might have caused that

**Comment by quadrophobiac** [comment]
@dicknorris - if you happen to have the CSV which triggered the error for downloading the file it would help a lot, haven't been able to reproduce the error using other CSVs on live, Mongoid::Error only reports when I do the following on localhost
- upload a CSV
- on validation page, download the csv
- on success copy URL that the 'Download Standardised CSV'
- navigate to this URL
- error should trigger

However on live this error doesn't reoccur. Navigating back and forth between the Standardised CSV URL doesn't trigger any catastrophic errors, however if the user navigates back using the browser back button the CSV file download process begins anew.*
There is a delay between clicking download and the file becoming available for saving to local system. If the user initialises the download procedure once they can click the download button multiple times and they will only have to experience the delay once. 
If they navigate away then they will experience the delay on each fresh issue of a download request

**Comment by quadrophobiac** [comment]
blocking pending clarification on either CSV that was used or a way to access the logs around the time the error occurred

**Comment by quadrophobiac** [comment]
file uploaded wasn't a CSV - creating more instructive user upload as enhancement and correcting the gem not reporting excel warning
Gem Fix = https://github.com/theodi/csvlint.rb/pull/149
UX https://github.com/theodi/csvlint/issues/227

**Comment by quadrophobiac** [comment]
PR for UX https://github.com/theodi/csvlint/pull/228

**Comment by quadrophobiac** [comment]
PR for excel https://github.com/theodi/csvlint.rb/pull/149
