### ISSUE TITLE
Get CSV on the Web updates into the CSV Lint app

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#741]
The changes will initially be moved into CSVlint.rb; we need to move them into the main app.

**Comment by quadrophobiac** [comment]
this ticket has pointers to some logic that will need changing in the rails app if the CSVW branch and its changes to the schema methods are merged https://github.com/theodi/csvlint.rb/issues/148

**Comment by quadrophobiac** [comment]
VCR causes tests to fail above and beyond the need for removing deprecated ` Csvlint::Schema.load_from_json_table`

**Comment by pezholio** [comment]
Superceded by #767
