### ISSUE TITLE
Ensure last updated properly tracks all edits in Pathway

### ISSUE THREAD

**Issue by ldodds** [theodi/shared#744]
https://github.com/theodi/pathway/issues/187

**Comment by pezholio** [comment]
@ldodds No

**Comment by pezholio** [comment]
@ldodds Whoops! Early submit there. What I meant to say what "Not sure what you mean here - can you explain in a bit more detail?" Should it be autosaving?

**Comment by ldodds** [comment]
I think what's happening here is that when someone is answering a question, or revising an answer its not updating the timestamp on the assessment too. That timestamp is only updating when the assessment model itself changes, not the dependent relationships.

So its just a matter of making sure the existing timestamp updates whenever answers are created/updated as well as changing the assessment fields too.

**Comment by pezholio** [comment]
I've just tested this, and it seems to update fine. Think https://github.com/theodi/pathway/pull/244 fixed it :smile:
