### ISSUE TITLE
Develop plan for revising organisational admin feature in Pathway

### ISSUE THREAD

**Issue by ldodds** [theodi/shared#761]
We need to identify how the revise the organisational admin functionality in Pathway. Currently its limited to one user per organisation, but this needs to be more flexible.

See some discussion here:

https://github.com/theodi/pathway/issues/284

Suggest we arrange time to discuss and develop/plan proposal

**Comment by pezholio** [comment]
Got a hangout with @ldodds on Friday to discuss this
