### ISSUE TITLE
Add the Open Data Monitor logo onto the 'About' section of the Certificates site

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#762]
See: https://github.com/theodi/open-data-certificate/issues/1283

**Comment by pezholio** [comment]
@ayymanduh - Have you got a copy of the ODM logo for this?

**Comment by ayymanduh** [comment]
![odm logo](https://cloud.githubusercontent.com/assets/6029876/10332507/9f45e5e8-6cd5-11e5-8f4c-a4f5cc0579b1.png)

This one please @pezholio 

Thanks!
