### ISSUE TITLE
Staging platform for member directory

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#780]

**Comment by pikesley** [comment]
This lives: http://staging.directory.theodi.org/members

However, I connected it to a dummy queue, but I've now found out it needs to talk to our tests accounts for Capsule and Xero &c.

Does this mean we're going to need a staging services-manager too?

**Comment by pezholio** [comment]
Should just need a staging Redis queue to work I'd have thought. Just depends how far down the path this stuff needs to be tested. Would be good to have though.

**Comment by pkqk** [comment]
if it's dependent on other services, I guess we should have a full staging environment.

maybe this should all be set up under `*.staging.theodi.org` instead of `staging.*.theodi.org` and have 2 fully independent environments.

**Comment by pikesley** [comment]
Andrea wants it to talk to Capsule and Xero and whatever else. +1 for @pkqk's idea above
