### ISSUE TITLE
Autocertification explanation messaging

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#793]

**Comment by Floppy** [comment]
This was messaging that @shevski had given to @dicknorris I think? Need to track it down...

**Comment by Floppy** [comment]
https://docs.google.com/document/d/1FArnOAE-CAnCujwVh8M02WjNc1A3qfaZHg14o8-DceA/edit

**Comment by Floppy** [comment]
* [ ] Create new page for autocert text (in doc)
* [ ] Add paragraph to FAQ (in doc)
* [ ] Update about page text; @shevski to describe what's needed.

**Comment by shevski** [comment]
Changes to 'About' page: https://certificates.theodi.org/en/about

1. Add link to 'Auto-certification' page at the top & remove link to 'How to get Certificates'
2. Change first bit of text from:

![screen shot 2016-01-14 at 10 18 11](https://cloud.githubusercontent.com/assets/1260289/12321822/233d41d2-baa8-11e5-870d-3813cc9cacef.png)


to:

Open Data Certificate is a free online tool developed and maintained by the Open Data Institute, to assess and recognise the sustainable publication of quality open data. It assess the legal, practical, technical and social aspects of publishing open data using best practice guidance.

Have a look at our [guide to what you need](https://certificates.theodi.org/en/about/whatyouneed) to complete a certificate or [start the questionnaire](https://certificates.theodi.org/en/surveys/e1KKmQo1cw/start) to create your own certificate now.

More information on the what, how and why of Open Data Certificates can be found on our [FAQ page](https://certificates.theodi.org/en/faq).

===

Then copy in section on 'How to get certificates' (lower case 'c')
.. adding in 'Find out more about auto-certification' line at the end of the multiple dataset section which links through to new auto certification page.

Then the rest of the existing sections on benefits

**Comment by pezholio** [comment]
All done, and ready to merge here https://github.com/theodi/open-data-certificate/pull/1373

**Comment by pezholio** [comment]
PR is here now, going straight to master https://github.com/theodi/open-data-certificate/pull/1374
