### ISSUE TITLE
Tweak certificates level table 

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#795]
There is a table which sets out the different criteria for each certificate level.  This needs updating to make sure that each level is correct.

Ira/Richard to get sign off from Jeni.  Table to then be updated on the website.

**Comment by Floppy** [comment]
@rnorris can you post an update on the state of this?

**Comment by pezholio** [comment]
Is it anything like the Czech version here? https://certificates.theodi.org/cs/about/badgelevels There's something commented out on the English version too

**Comment by quadrophobiac** [comment]
This issue was moved to theodi/open-data-certificate#1542
