### ISSUE TITLE
Line heatmap vis

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#807]
Show heatmap on entire line to show congestion. Not individual trains, just show heatmapping based on train position.

- [ ] What are we mapping?
  * People in a station at a given time?
  * How busy the trains are?
  * Shading whole sections of line? (requires more than one train)
- [ ] Draw the Victoria Line in CSS / HTML

**Comment by pikesley** [comment]
Can we do this, seeing as we have but one train?

**Comment by pezholio** [comment]
I was thinking we show the position of the train at any given time. We can fake the train number, or rather just act like it's not there

**Comment by pezholio** [comment]
We could also show the progress of the train as it progresses along the line, and maybe even speed up time a la https://traintimes.org.uk/map/#bhm

**Comment by Floppy** [comment]
Replaced with more detailed tickets
