### ISSUE TITLE
Fix Application Error following a deply

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#809]

**Comment by pezholio** [comment]
We tried to fix this in https://github.com/TheODI-UD2D/sir_handel/pull/21 - However, I don't think this is working in practice. This - https://github.com/TheODI-UD2D/sir_handel/blob/master/lib/sir_handel.rb#L32 should be running on boot and setting up the lookups and aliases, which should work in theory, assumuning the singelton is remaining in memory, but it seems that it's not working in practice. Suspect we may need to go down to the gem level to fix this, which I didn't really want to do
