### ISSUE TITLE
Rebrand certificates

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#816]
* [x] badge graphics
* [x] copy

See https://docs.google.com/document/d/15I_xGlTzQW8vtsG2Nm9xBmyOqwmdMJ132BHDAo403V8/edit?ts=568e4307# for what needs doing.

To launch on Tuesday 19th.

**Comment by pezholio** [comment]
This is in a PR here https://github.com/theodi/open-data-certificate/pull/1371 ready to merge to staging and be checked

**Comment by shevski** [comment]
Changes to staging re: badge rebrand

[x] http://staging.certificates.theodi.org/en/faq - last, auto certification needs updating Raw -> Bronze
[x] http://staging.certificates.theodi.org/en/datasets/162389/certificates/193578/improvements - ‘The basics’ -> ‘Bronze Requirements'
[x] Embed popup - e.g. on any certificate page (http://staging.certificates.theodi.org/en/datasets/162293/certificate) when you click ‘embed this on your site’ does not display badge and need to test that embed code works properly
![screen shot 2016-01-20 at 13 46 21](https://cloud.githubusercontent.com/assets/1260289/12450797/bd71a9e4-bf7d-11e5-8124-9c3ce5150126.png)

**Comment by shevski** [comment]
one other 'nice to have' but perhaps should be a separate ticket

http://staging.certificates.theodi.org/en/datasets - would be nice to see the level awarded, perhaps next to the badge icon. Could be badge icon, then name {Bronze / Silver / Gold / Platinum}, title; or as a separate column heading (there in a largish page, between ‘view certificate’ button and ‘published by’ section, this ought to be rejigged to leave more space for dataset / certificate heading

**Comment by Floppy** [comment]
Re: the embedding, I wonder if this is because of HTTPS URLs in there and the fact that that doesn't work properly at the moment.

**Comment by Floppy** [comment]
Confirmed, the embed problem is because of HTTPS being used, but broken on certificates staging. If you add a security exception for HTTPS on staging, the embed dialog looks fine:

**Comment by Floppy** [comment]
Again, two out of 3 done here on `feature-rebrand` , but the one remaining isn't on that branch. Will see about fixing it elsewhere, otherwise will let @pezholio do it when he gets in tomorrow.
