### ISSUE TITLE
Export active user emails from certificates

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#821]
Export of all certificate users email addresses (ideally *not including those who did not actually create an account or know about certificates*…)

Want: CSV of names and emails. Import into mailchimp (talk to production) probably to mail out an update.

**Comment by pezholio** [comment]
Do we only want users that have created certificates? That should filter out the crap spam accounts

**Comment by Floppy** [comment]
Users who have:
 * created a dataset
 * actively logged in
