### ISSUE TITLE
Fix openaddresses SSL certificate

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#824]

**Comment by pikesley** [comment]
I have tried letsencrypt. It's a rabbit-hole.

* It needs a static file on the target host. Fine, I can do this
* It will _only_ connect to the target host on port 80
* We have SSL enabled on Heroku _and_ Cloudflare (I think)
* I tried to (temporarily) disable SSL on Heroku:
  ![uploads/be22f54f-f8c4-44f7-b498-1fb77b773831/Screenshot 2016-01-12 11.18.55.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbe22f54f-f8c4-44f7-b498-1fb77b773831%2FScreenshot+2016-01-12+11.18.55.png)
* SSL on Cloudflare seems to be set to 'flexible' and configured _for the whole domain_. I switched it off (I think) but I'm still getting forced through (broken) SSL
* I want to set it all on fire

**Comment by pezholio** [comment]
Oh man. Have we got budget to stick with Cloudflare then?

**Comment by Floppy** [comment]
The forced SSL is probably done with a redirect on the cloudflare config... that might still be active?

**Comment by Floppy** [comment]
But yes. If cost of new certificate < cost of time to work out letsencrypt, then let's just buy it and move on.

**Comment by pikesley** [comment]
@JeniT can we have some money please?

**Comment by pezholio** [comment]
https://www.youtube.com/watch?v=ta8z_Hg0fgI

**Comment by pikesley** [comment]
https://www.youtube.com/watch?v=HeN8saLI1IE for some reason

**Comment by pikesley** [comment]
CC failure :(

**Comment by pikesley** [comment]
It's in, Heroku shows it as kosher:

    ➔ heroku certs:info
    Fetching SSL Endpoint oa-ernest.herokuapp.com info for oa-ernest... done
    Certificate details:
    Common Name(s): *.openaddressesuk.org
                openaddressesuk.org

    Expires At:     2017-01-13 23:59 UTC
    Issuer:         /C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2 
    Starts At:      2016-01-13 00:00 UTC
    Subject:        /OU=Domain Control Validated/OU=Gandi Standard Wildcard SSL/CN=*.openaddressesuk.org
    SSL certificate is verified by a root authority.

But it's still showing as busted. I'm blaming caching and will revisit in the morning

**Comment by pikesley** [comment]
The problem, as so often, was between the steering-wheel and the seat: I had applied the cert to the wrong Heroku app. I have now applied it to the correct app, and it works: https://alpha.openaddressesuk.org/
