### ISSUE TITLE
Set up proxy for TfL

### ISSUE THREAD

**Issue by pezholio** [theodi/shared#825]

**Comment by pikesley** [comment]
I think this might all be futile: I've set up [tinyproxy](https://tinyproxy.github.io/) on a Digital Ocean droplet, and it works great. However, yesterday the source IP was showing as `141.101.99.157`. Today it's `141.101.98.10`. Neither of these are `46.101.91.216`, the actual IP if the droplet.

Clouds.

**Comment by pezholio** [comment]
Da fuq? Can we get a fixed IP from Digital Ocean?

**Comment by pikesley** [comment]
We get a fixed _inbound_ IP. I suspect outbound IPs are dynamic by design. Clouds.

**Comment by pezholio** [comment]
Maybe this will help? https://www.digitalocean.com/community/questions/ha-setup-how-to-get-all-outbound-traffic-to-come-from-single-ip

**Comment by pikesley** [comment]
Oh good *adds points to ticket*

**Comment by pezholio** [comment]
![](http://i.imgur.com/91sn32Q.jpg?fb)

**Comment by pikesley** [comment]
*learns iptables*

**Comment by pikesley** [comment]
This doesn't work. I could spend the rest of the week working out how to do this, or we could attempt to push the problem upstream

**Comment by pezholio** [comment]
Grrrr. So basically we need a dedicated box to get this to work? That's annoying.

**Comment by pikesley** [comment]
Like a *real* box. Actual iron. And even then, we're at the whim of upstream, I think

This is not how we do things in 2016
