### ISSUE TITLE
Updates to staging about page to go live on Thursday

### ISSUE THREAD

**Issue by shevski** [theodi/shared#834]
http://staging.certificates.theodi.org/en/about
- [x] remove ‘vision’ header
- [x] remove ‘how to get certiticates’ link & page at the top
- [x] add ‘auto-certification’ link & page link at top
- [x] paste in content of ‘how to get certificates’ into NEW section on about page above ‘publisher benefits; (to reduce number of separate pages) titled ‘How to get certificates’ (lower case c)

**Comment by Floppy** [comment]
Ticked changes above done on `feature-rebrand` branch, though I don't have the autocert page on there, so that one's not done yet. I'm a little confused with ODC branching strategy, so I don't want to break anything. Will leave that one for the morning when @pezholio is back.
