### ISSUE TITLE
Names of Dundee student members not uploaded  URGENT

### ISSUE THREAD

**Issue by Juliehitgub** [theodi/shared#835]
Spreadsheet for Dundee had 770 students, which was uploaded in batches before Christmas. Chargify and Capsule each have record of 688. 
So far have been able to locate these ten students by name that don't appear on the system. Can the following people be checked to see if they are actually in the system somewhere but just not showing up Chargify/Capsule?
Trying to establish if they need to be uploaded again. 

David Boldrin
James Bowden
Connor Bowen
Polyxeni Bozatzi
Thiago Britto Borges
Emma Bryder
Natasha Burr
Marco Canizares
Anne Canny
Zhenping Cao
Teresa Cardote

**Comment by Floppy** [comment]
None of these have records in the member directory either, so they need re-uploading. You can check these in future by searching the members at https://directory.theodi.org/admin - I'll show you how when I'm in the office if you have trouble.

I've now removed the names from the ticket here as it's publicly visible.

**Comment by Juliehitgub** [comment]
Oh-no,  forgot it that info visible James, thanks for taking it down.
Really useful to know they are not there, will upload asap. I need to
locate a total of 93 'missing' from Dundee uploads. It would be really
helpful to be shown how to search admin, I'll try and find the others and
do it one go.



Julie McMahon, Membership Administrator
+44 (0) 20 3598 9395

The Open Data Institute, 65 Clifton Street, London EC2A 4JE
<http://www.theodi.org/>

**Comment by Juliehitgub** [comment]
The link takes me to members, I don't seem to have admin access.

Julie McMahon, Membership Administrator
+44 (0) 20 3598 9395

The Open Data Institute, 65 Clifton Street, London EC2A 4JE
<http://www.theodi.org/>
