### ISSUE TITLE
[ODC] questionnaire wording updates have reverted

### ISSUE THREAD

**Issue by shevski** [theodi/shared#855]
1. Create a new certificate
2. Compare questions to those they were updated to: https://docs.google.com/document/d/1V1xAnPuoc5-SVqBK68fdWBq42yHo7OWJDTvubqLQbmg/edit
3. Panic

Note that part of the wording changes included some swaps in ordering and logic

**Comment by Floppy** [comment]
Ah, so all the wording changes in that doc appear to have been rolled back?

**Comment by shevski** [comment]
yes

**Comment by pezholio** [comment]
When was this last known to be working? Trying to track down the changes that triggered it, but it's proving tricky

**Comment by shevski** [comment]
Where are we with this? Text changes don't seem to be live yet (or at least not all of them)

**Comment by pezholio** [comment]
Which ones specifically? AFAIK they should all be live now

**Comment by shevski** [comment]
Hmm, so far can't find any of the new help text (the stuff that appears on hover) https://docs.google.com/document/d/1V1xAnPuoc5-SVqBK68fdWBq42yHo7OWJDTvubqLQbmg/edit

**Comment by shevski** [comment]
And in fact most of the questions still have the old wording - e.g. 'What kind of data do you publish?'
@pezholio maybe worth having a quick call about this?

**Comment by pkqk** [comment]
The changes had been made to the definition files in `/prototype` but not in the ones in the newer setup, it must've got out of sync at some point.
