### ISSUE TITLE
Flexible pricing for individual membership

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#875]
As a potential individual member of the ODI, I want to be able to choose my own price point so that I can pay what I think membership is worth or what I can afford.

* [x] Add dropdown to select pre-selected prices, e.g. £100, £90, £70, £60, £50, £40, £30, £20, £10, £5, £1.
* [ ] Add freeform price field so people can choose their own.
* [x] Rewire internal glue code to pass through pricing to invoicing.
* [x] Update details in Chargify to allow flexible pricing. Might require having specific products at different prices, which might preclude the "choose your own" option.
* [x] Update welcome emails for individual membership.

Should be ready for internal testing 19th Feb. Due for launch on 29th Feb.

**Comment by Juliehitgub** [comment]
Flexible pricing email, 
1. for picture at top of email, please crop a rectangular section from slide 13, (abstract circles) from Summit15-BFI-EXISTING-COLLATORAL.pdf on the drive
2. for body of text please contact RL

Student Welcome email. Please could the picture on our Welcome email for students be updated from same source as above. Rectangular crop from Slide 3, (pink odi logo w/ heart) and replace existing picture with this one.

**Comment by pezholio** [comment]
The main changes are here https://github.com/theodi/member-directory/pull/642 and here https://github.com/theodi/open-orgn-services/pull/502. Just need text from Rachel to do the emails

**Comment by Juliehitgub** [comment]
Thanks, that's great stuff. I'll ask her to send the text on to you asap.

Been creating and testing links for more students to sign up, noticed that the old picture is still on the email, is it possible to update as per message above?
