### ISSUE TITLE
Show progress bar for schema files (CSV lint)

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#886]
See original CSV lint ticket #250
https://github.com/theodi/csvlint/issues/250

"See #249

At the moment, these are uploaded on submit, but this could be confusing, as you see a progress bar for the csv, but not for the schema, which may make users think something is wrong"

**Comment by Floppy** [comment]
Faked for now, just to give consistent user feedback, but could be wired through for real later on.

**Comment by pezholio** [comment]
PR here https://github.com/theodi/csvlint/pull/255
