### ISSUE TITLE
Design rpi hardware

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#892]

**Comment by pezholio** [comment]
I think I've got this nailed now - I went out and bought another kit from Maplins which uses direct connections without a breakout board - see https://github.com/TheODI-UD2D/walvic/blob/master/pi-setup.jpg @pikesley should be able to source some similar at Maplin.

**Comment by pezholio** [comment]
Instructions for setup are here https://github.com/TheODI-UD2D/walvic
