### ISSUE TITLE
Launch the Membership pay what you like

### ISSUE THREAD

**Issue by pezholio** [theodi/shared#898]

**Comment by Floppy** [comment]
Still to do:

* [ ] Changes to new [member email](https://docs.google.com/document/d/1fPFP7alorps97YyMdCp8meeIt42ZRGNSYqis5SBtIXo/edit)
* [ ] Updated [T&Cs](https://docs.google.com/document/d/18Y9GLBsbaG_zu63-1A3A0V808Ll-LymW72C3eKPW2hY/edit#heading=h.1m19kf7n3j4q)

**Comment by pezholio** [comment]
All done - and the services code is already in production. Just need to merge and we're good to go :+1:

**Comment by pezholio** [comment]
Everything in in place and working. Say hello to the newest ODI member - me!
