### ISSUE TITLE
Add learning build environments to github

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#907]
LMS and Cordova build environments in github

* LMS is already in Heroku, and is 12-factor safe, so we can just add that to github and add an OSS license.
* Cordova we need to work out what a clean build environment looks like and add it in.

**Comment by pezholio** [comment]
LMS is there, and I've added Cordova to the eLearning repo - just waiting on @davetaz to give me a yay or nay https://github.com/theodi/ODI-eLearning/pull/363
