### ISSUE TITLE
Email templates for learning engagement

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#908]
Email templates for first engagement and saving progress

Technologies: PHP, Mandrill, Mailchimp 

there is already a sendEmail method, which sends the appropriate emails, but it needs:
* prettifying
* changing link to primary domain for theme. LMS DB does not currently contain primary domains for the themes, that will need adding (possibly managed via a googledoc).
* splitting into per-language and per-theme templates.

question: is there template functionality in one of the mandrill/mailchimp services that we could use to allow people to easily manage or make new templates rather than adding them in as static templates?

**Comment by pezholio** [comment]
So, we can now use templates, and the ODI one works. I guess the next step is making new per-language and per-theme templates, but then switching between them should be easy. Not sure how far along the road we are with this yet - @davetaz any ideas?
