### ISSUE TITLE
Sort out mandrill changes

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#912]
Mandrill is changing. Some things we can continue to use when we merge with the mailchimp account, but some heroku apps might be better transitioned to SendGrid.

**Comment by pezholio** [comment]
I've already merged the Mailchimp account, so those should Just Work. We can probably just use the API key of our main Mandrill account in the Heroku apps and delete the plugin

**Comment by Floppy** [comment]
Nice. I've had a separate warning for the pathway app on Heroku, so that's one that needs switching over...

**Comment by pikesley** [comment]
Moved Pathway, think this is the last one
