### ISSUE TITLE
Work out metrics alpha product definition

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#914]

**Comment by pezholio** [comment]
A lot of the work we've done has been to handle the edge cases that we have. I reckon we need to reduce scope to handle only time series data in the following format:

```
{
  "time": "2016-03-06T12:52:38.000+00:00",
  "value": 286
}
```

The question is, do we want to validate against this format, or do we want to make it as unrestrictive as possible? I guess as it's alpha, then that's fine, and also won't break anything for us.

**Comment by pezholio** [comment]
Some other ideas:

* A gh-pages website with installation instructions and background info (so we can point people at that rather than our own installation)
* Single views show numbers by default
* Do we want to do dashboards?

**Comment by Floppy** [comment]
Let's add these directly to https://github.com/theodi/metrics-api/issues
