### ISSUE TITLE
Experiment with JKAN

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#915]

**Comment by Floppy** [comment]
@pezholio can you drop links in here to the PRs we've sent upstream?

**Comment by pezholio** [comment]
Yup!

https://github.com/timwis/jkan/pull/75 - merged
https://github.com/timwis/jkan/pull/81 - not yet merged

**Comment by pezholio** [comment]
I'm gonna call this closed now - I'll open up a seperate PR for blogging, and will obviously do more as time goes on
