### ISSUE TITLE
Make sure that VCU is accounted for correctly in Train Data Demo

### ISSUE THREAD

**Issue by dicknorris** [theodi/shared#921]

**Comment by dicknorris** [comment]
304 = Southbound
306 & 308 = Middle
310 = Northbound

**Comment by pezholio** [comment]
I've made some changes to the code so we can filter by VCU, and this has revealed there's quite a few holes:

None of the days I tried had _any_ data for 306 or 308

Some days had data for 304 and 310, while other days had data for 304.

Unless we're missing something, I'm not sure we can do anything more with what we have :(
